### PR TITLE
Networkchart ver 0.0.6 [gramps42]

### PR DESCRIPTION
**Pull request by zorkmark**
Rewrite to use any of the following dot interfaces (still needs networkx installed):
  pydotplus
  pydot
  pygraphviz
  dot 
  dot.exe (included with Gramps)

So python modules for dot access are no longer required but will automatically be used if available.  If those are not found the dot package or dot.exe executable will be automatically used.  Python module **networkx** is still required to function.

Scaled back auto-set separation between "generations" for large databases (3" to 2").

Includes ver_0.0.5 fixes:
  Fixed PersonOption initial value Warnings on command line.
  Fixed "Signal recursion blocked" Warnings on command line.
  Converted to python standard configparser for ini file.

This should be the last update to 42.   Will begin work on integrating to 50.

### CODE REVIEW

**Comment by zorkmark** [comment]
Apologies, clicked the request to review button by mistake.  No rush.  

Do have a question for anyone though.  Is there a way to install a python module in the Windows AIO environment without packaging it?

**Comment by prculley** [comment]
Depends on the 'module'.  If it is a user plugin, you can just drop it into
the C:\Users\NAME\AppData\Roaming\gramps\gramps50\plugins using a
sub-directory like other plugins installed there.  It would need the '
xxx.gpr.py' and the 'xxx.py' files at least.

If it is a Gramps python file, you can just put it into the
C:\GrampsAIO64-5.0.0\gramps folder in the appropriate sub-directory.
If it is a python library, that is more involved...

Paul Culley

**Comment by zorkmark** [comment]
That answered my question, thank you.  I'm able to install libraries in the development environment msys2/mingw but was curious if there was a simple way to add to the already packaged AIO.  Sounds like it would be a bit more involved.

**Comment by sam-m888** [comment]
>> Apologies, clicked the request to review button by mistake. No rush.

So you only want @Nick-Hall to review or can anyone else?

>> This branch has conflicts that must be resolved

Either way can you please rebase your PR, so that when ready it can be merged?

**Comment by zorkmark** [comment]
Anyone that can review is welcome##SELECTION_END##.  Will rebase and
resubmit PR.

Thank you,

Mark

-----Original Message-----

**Comment by sam-m888** [comment]
FYI found this on the mailing list. 

> Besides, as I use a Dutch version of Linux Mint I still was not able to use the new Network Chart report.
> But when I changed my language to English it worked like a charm...

http://gramps.1791082.n4.nabble.com/Network-Chart-Report-Installation-Errors-tp4679692p4679716.html

**Comment by sam-m888** [comment]
Tested the latest version on Linux (Xubuntu 16.04) and used all the options I could and was unable to break it 👍  

Only tested in the [English language](https://github.com/gramps-project/addons-source/pull/67#issuecomment-301211974).

One minor issue was that the Help button goes incorrectly to:

* https://gramps-project.org/wiki/index.php?title=Gramps_4.2_Wiki_Manual_-_Reports#Network_Chart

instead of to:

* https://gramps-project.org/wiki/index.php?title=NetworkChart

example-networkchart-v006

**Comment by sam-m888** [comment]
Another thing to be aware of is that if you run a chart on one family tree and then open up another family tree and then look at the **Trim** or **Highlight** tabs you will notice that the individuals previously chosen on the original family trees Gramps id is used again against the second family tree and may make no sense at all this includes the **Highlight** tabs "Center person" not using the second family trees active person as expected.  Probably best to keep a separate set of setting per family tree.

**Comment by adamvazquez82** [comment]
Any timeline on when this will be available?

**Comment by prculley** [comment]
@zorkmark Has this been abandoned?
@adamvazquez82 As with all things open source, the answer is "when the volunteer gets to it."  I would release it but someone has put the 'work in progress' flag on it which suggests that it is not considered finished.  And as I am not the author, I have no idea of what that might be...

**Comment by adamvazquez82** [comment]
> someone has put the 'work in progress' flag on it which suggests that it is not considered finished. And as I am not the author, I have no idea of what that might be.

@sam-m888 Should the flag be removed?

@prculley Understood thank you.

**Comment by sam-m888** [comment]
> but someone has put the 'work in progress' flag on it which suggests that it is not considered finished. And as I am not the author, I have no idea of what that might be...

@prculley That was me and the WIP flag was added specifically because this pr needed to be rebased. Then @zorkmark asked for a [review](https://github.com/gramps-project/addons-source/pull/67#issuecomment-299632613) which I provided but the pr as is could be committed and my review/issue  added to mantisdb, as this pr would if I recall benefit ms-windows users so that they can ignore "Dismiss" this add-on on the AIO version while @bpisoj  is away and Gramps 4.2.6 for windows has not been created....

**Comment by sam-m888** [comment]
Manually commited as https://github.com/gramps-project/addons-source/commit/23d3990a14b6fc1e554d3e9487fd3845bd3da446 to gramps42  and rebuilt https://github.com/gramps-project/addons/commit/69c10c62dbb5a2ad054ad2425b1b3fde95ffddc8

**Pull request closed without merging**
