### PR TITLE
Add more Ukrainian translations

### PR DESCRIPTION
**Pull request by Illia-M**
Continue add more Ukrainian translation for addons

### CODE REVIEW

**Comment by Fedik** [comment]
Thank you!

**Comment by GaryGriffin** [comment]
@Fedik @Illia-M 

This PR broke the UK translation for Graphview. When I merged an updated Graphview, I got the following error. Please fix the GraphView translation

GraphView/po/uk-local.po:82: 'msgid' and 'msgstr' entries do not both begin with '\n'

**Comment by Illia-M** [comment]
@GaryGriffin ok, I create one more PR this fix of such issues, as I understand lines in translations cannot be \n char

**Comment by Fedik** [comment]
@Illia-M ping me then

> as I understand lines in translations cannot be \n char

It can, just like that https://github.com/gramps-project/addons-source/blob/d478fc608e624af6bfacb9d53ffde465c21784c4/GraphView/po/uk-local.po#L70-L73

**Comment by Illia-M** [comment]
@Fedik as I understand template updated and this messages can be removed, some changes wait on notebook to push) https://github.com/gramps-project/addons-source/pull/627
I'm here and can fix comments asap

**Pull request merged**
