### PR TITLE
Update DetailedDescendantBookReport.py

### PR DESCRIPTION
**Pull request by giansgusi**
implemented the following features :
1. index of names
2. index of dates
3. index of places

### CODE REVIEW

**Comment by dsblank** [comment]
Great; thanks! What version of Gramps would you like this included in?

**Comment by giansgusi** [comment]
Hi Doug,
I'm using Gramps 4.1.3.-1 and don't know the exact roadmap of Gramps...
let's say I'd like to have this feature on any future version. Does it make
sense ?

Thanks to you.

Giansalvo

2015-07-13 13:59 GMT+02:00 Doug Blank <notifications@github.com>:

**Comment by dsblank** [comment]
Yes, thanks. I'll generate for gramps41, gramps42, and gramps50.

**Comment by dsblank** [comment]
Done for gramps42, and gramps50. Will require some work to get over to gramps41...

**Pull request merged**
