### PR TITLE
Updated DNA gramplet

### PR DESCRIPTION
**Pull request by GaryGriffin**
Updated DNA gramplet with user feedback. Added color background, additional tooltip text, changed input data format to remove M/F/U flag and add SNP (optional), and add Legend. This is in addition to the refresh fix, overlay of all Associate graphs.

### CODE REVIEW

**Comment by PQYPLZXHGF** [comment]
Installed new v1.0.5  and Gramps crashes with the following error:

```
83437: ERROR: grampsapp.py: line 157: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gui\viewmanager.py", line 871, in view_changed
    self.__change_page(page_num)
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gui\viewmanager.py", line 882, in __change_page
    self.active_page.set_active()
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gui\views\listview.py", line 293, in set_active
    NavigationView.set_active(self)
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gui\views\navigationview.py", line 153, in set_active
    PageView.set_active(self)
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gui\views\pageview.py", line 328, in set_active
    self.bottombar.set_active()
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gui\widgets\grampletbar.py", line 275, in set_active
    gramplet.pui.update()
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gen\plug\_gramplet.py", line 311, in update
    self._generator = self.main()
  File "C:\Users\PQYPLZXHGF\AppData\Roaming\gramps\gramps51\plugins\DNA\dna.py", line 104, in main
    cms = float(field[3])
ValueError: could not convert string to float: 'M'

```

I believe the gramplet is trying to parse the previous dna gramplets csv format information  and failing , maybe have the gramplet totalty ignore incorrect csv data.

Great Gramplet thanks 🥇

**Comment by Mattkmmr** [comment]
@PQYPLZXHGF The imput data in association notes has changed. The maternal/paternal side flags (M, P or U) are no longer used and have to be removed manually. [More information](https://gramps.discourse.group/t/updated-dna-gramplet-ready-for-review/807/27).

**Comment by PQYPLZXHGF** [comment]
@Mattkmmr Though as much, thanks for the confirmation 👍   hopefully the update version is more bullet proof and forgiving of errors.

https://github.com/gramps-project/addons-source/pull/469
https://github.com/gramps-project/addons-source/pull/465

**Comment by prculley** [comment]
FYI; it is not necessary to close a PR when changes are made.  It is often easier to understand changes in context if you simply add commits (or even force push a completely modified set of commits).  That way others may be able to figure out why changes were made.  You decide...

**Pull request closed without merging**
