### PR TITLE
[MediaReport] A media text report [gramps51]

### PR DESCRIPTION
**Pull request by Mattkmmr**
The **Media Report** is a text report for images. The report allows custom headings and custom notes as well as the image data like notes, citations, tags, attributes and people references. 
* [Wiki dokumentation here](https://gramps-project.org/wiki/index.php/Addon:MediaReport) 
* [Issue #11239 on Bugtracker](https://gramps-project.org/bugs/view.php?id=11239)

**Option Dialog Sample:**
MediaReport dialog

**Sample Report:**
MediaReport Example

### CODE REVIEW

**Comment by lordemannd** [comment]
got it to work on my machine.
just simple testing so far.

found 1 problem, if the box for adding custom note is check, but no note is actually selected, I got the Error Report Wizard with:
566551: ERROR: _reportdialog.py: line 748: Failed to run report.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gramps/gui/plug/report/_reportdialog.py", line 709, in report
    my_report.write_report()
  File "/home/dave/.gramps/gramps51/plugins/MediaReport/media_report.py", line 90, in write_report
    self.write_note()
  File "/home/dave/.gramps/gramps51/plugins/MediaReport/media_report.py", line 353, in write_note
    self.doc.write_styled_note(note.get_styledtext(), note.get_format(),
AttributeError: 'NoneType' object has no attribute 'get_styledtext'

**Comment by PQYPLZXHGF** [comment]
Experienced something similar here when I unticked all the options and did not choose an image 

> 339788: ERROR: _reportdialog.py: line 748: Failed to run report.
> Traceback (most recent call last):
>   File "C:\Program Files\GrampsAIO64-5.1.0\gramps\gui\plug\report\_reportdialog.py", line 709, in report
>     my_report.write_report()
>   File "C:\Users\me\Documents\gramps-test-profile\gramps\gramps51\plugins\MediaReport\media_report.py", line 79, in write_report
>     path = media.get_text_data_list()[0]
> AttributeError: 'NoneType' object has no attribute 'get_text_data_list'

**Comment by PQYPLZXHGF** [comment]
@Mattkmmr Is it possible If I do not select an image the report will assume I want a pdf with all images, or at least popup a message saying report cannot run without first selecting an image?

**Comment by lordemannd** [comment]
on Windows I got this ERW report:
210276: ERROR: _reportdialog.py: line 748: Failed to run report.
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.0-WORK\gramps\gui\plug\report\_reportdialog.py", line 709, in report
    my_report.write_report()
  File "C:\Users\dave\AppData\Roaming\gramps\gramps51\plugins\MediaReport\media_report.py", line 86, in write_report
    self.write_media(path)
  File "C:\Users\dave\AppData\Roaming\gramps\gramps51\plugins\MediaReport\media_report.py", line 274, in write_media
    width = self.doc.get_usable_width() * 0.8
AttributeError: 'HtmlDoc' object has no attribute 'get_usable_width'

**Comment by Mattkmmr** [comment]
* [x] Fixed error: 'include custom note' option checked, but no node was selected + message
* [x] Fixed error: no image/media selected + message
* [x] Added feature: report now checks if the media file is an image + message
* [x] Added feature: note selection gets disabled if 'include custom note' option isn't checked
* [x] Added feature: users now get informed with a message that the report only works with PDFs as output file format

@lordemannd: The UNKNOWN people references can only be added with a placeholder person named UNKNOWN. Gramps removes photo references/tagged areas if no person is referenced to it.

@PQYPLZXHGF If you do not select an image, you'll get a message now that one is required.

**Comment by lordemannd** [comment]
Matt, I saw your question on the devel list. Where you asking if it would be acceptable for a text report (like this one) to only support PDF? Maybe Paul C. thought you were asking about making a change for all text reports.

**Comment by lordemannd** [comment]
testing of updated version:
- in add custom note is check, but no note, warning dialog is shown, but click on close button and an empty PDF is created and the PDF viewer launched.
- if RTF format selected, warning dialog is shown, clicking the close button, launches RTF editor/viewer with an empty file.

**Comment by sam-m888** [comment]
@Mattkmmr Is this ready to go as is?

**Comment by Mattkmmr** [comment]
@sam-m888 yes it's ready.

**Pull request merged**
