### PR TITLE
Error check for bad GOVid name

### PR DESCRIPTION
**Pull request by GaryGriffin**

### CODE REVIEW

**Comment by sam-m888** [comment]
Thank you

**Comment by uxcq** [comment]
@sam-m888 When you have a moment can you please rebuild this also?

**Comment by sam-m888** [comment]
I've rebuilt the addon for Gramps 5.0

https://github.com/gramps-project/addons/commit/
19e92753a2379f85a2e78e86c8540cceed4fb66a

And Nick Hall has added and built the addon for Gramps 4.2

https://github.com/gramps-project/addons/commit/
d6a8314a762342901c8221506d1ed769035c378f

**Comment by uxcq** [comment]
@sam-m888 Thanks 👍 , and I actually did mean for Gramps 4.2 so thank you to @Nick-Hall also 🥇

**Pull request merged**
