### PR TITLE
[PreReqChecker]List installed Locales[gramps50]

### PR DESCRIPTION
**Pull request by sam-m888**
Show more complete information about the language environment

Feature request [10952](https://gramps-project.org/bugs/view.php?id=10952)

Adds new section called  "**Locales available:**"

### CODE REVIEW

**Comment by lordemannd** [comment]
It, works for me, I tried 2 installs, adding US english and with addition of German.
I notice in both cases, the last language is repeated twice.

RESULTS With only US english installed:
Locales available:

Installed Locales (On Microsoft Windows if English is only listed please re-install Gramps again making sure to select all the Translations and Dictionaries 

en_GB : English
en : English (USA)
en : English (USA)

RESULTS WITH US english and German installed:
Locales available:

Installed Locales (On Microsoft Windows if English is only listed please re-install Gramps again making sure to select all the Translations and Dictionaries 

en_GB : English
en : English (USA)
de : German
de : German

**Comment by sam-m888** [comment]
> I notice in both cases, the last language is repeated twice.

Ok fixed.

**Comment by wroldwiedbwe** [comment]
@sam-m888 It's not only windows but also a number of the linux distributions have separate translations.

**Comment by sam-m888** [comment]
@wroldwiedbwe Thanks I'll make the message a bit more generic. 👍

**Comment by sam-m888** [comment]
Rebuilt addon for gramps50 in
https://github.com/gramps-project/addons/commit/dfb83b9f823123dca146c2a344e2231520b365ea

**Pull request merged**
