### PR TITLE
[GraphView] fixes (gramps50)

### PR DESCRIPTION
**Pull request by vantu5z**
- fix #10791 (escape symbols)
- reduce spaces in family node
- always use html for nodes labels
- review code

### CODE REVIEW

**Comment by SNoiraud** [comment]
I'll comment if I find problems. None for the moment.

**Comment by vantu5z** [comment]
Should we merge this PR?

**Comment by SNoiraud** [comment]
I think you can, I saw no problem since I use it.

**Comment by SNoiraud** [comment]
I have no access to it too.

**Comment by sam-m888** [comment]
Thank you

@SNoiraud Access permissions are managed by Nick Hall.

**Pull request merged**
