### PR TITLE
[SetPrivacy] A tool to mass-edit privacy [gramps51]

### PR DESCRIPTION
**Pull request by Mattkmmr**

### CODE REVIEW

**Comment by PQYPLZXHGF** [comment]
Works for me, but would be nice to have a list of what was changed?

Suggest the "Tool" have a more descriptive name than "Tool" ?

setprivacy1

**Comment by Mattkmmr** [comment]
@PQYPLZXHGF Thank you for your feedback. I updated the pull request for this tool:
* Add tool window name
* Notify users how many objects were set private and not set private
* Help text for 'Always privat' and 'Years' option

**Comment by Mattkmmr** [comment]
Wiki documentation and screenshot.
https://gramps-project.org/wiki/index.php/Addon:SetPrivacyTool
SetPrivacyTool

**Comment by sam-m888** [comment]
Thank you for both the addon and your patience 👍

**Pull request merged**
