### PR TITLE
Maintenance/gramps51

### PR DESCRIPTION
**Pull request by GaryGriffin**
Initial Checkin for Sync Association addon. This addon will create reciprocal Associations where missing.

### CODE REVIEW

**Comment by prculley** [comment]
It would be best to leave the PR open for a while, to allow others to comment on it.  We usually prefer about 10 days, unless it is very trivial.

**Comment by GaryGriffin** [comment]
Sorry, I am not really familiar with GitHub (I struggled for days to figure out how to checkin the files). Should I make some change to what I did or are you saying it should stay as is thru a comment period and then I have to do something? If the latter, what steps do I have to take after a comment period? If the former, what step should I not have done?

**Comment by prculley** [comment]
Just don't 'Merge' the PR right away.  That gives the developers and others a chance to examine the code for potential problems, and to perform some tests.  And perhaps suggest improvements.  In fact most people don't even have 'Merge' rights; the PRs they create have to be merged by one of the people with these rights, generally someone in the developers list.

These days, its mostly Sam, myself or Nick Hall that perform the merges (and have to go through the effort of building and listing the addon so users can get it from Gramps).

**Comment by Nick-Hall** [comment]
It is unlikely that a third-party addon would be rejected, especially if it doesn't write to the database.

Although the usual contribution rules don't apply to the `addons-source` repository, it may be helpful to leave the PR open for a few days if you are not familiar with git.

**Comment by GaryGriffin** [comment]
This add-on (SyncAssociation) does write to the database (adds Associations to existing people). I submitted another PR for an update (adding user feedback when executing, not writing to db). I left that PR open. The documentation is already updated.

BTW, I am working on the DNA gramplet now to make it more useful. I would really like to get feedback when I submit that PR. I am consolidating all of the Associations into a single graph (rather than having one per Association; color coding for each associated person; auto-detecting whether Maternal/Paternal (will use the M/P setting in the Associations Note iff there is no MRCA). And trying to fix the draw model (currently it reads the first time the DNA tab  is selected and never refreshes the data, so anyone with a DNA Association sees the same graph).

----
In the average US hospital visit, there are more people involved in billing you than treating you.

Gary Griffin

**Comment by GaryGriffin** [comment]
I submitted a pull request #410  for SyncAssociation Add-on about 2 weeks ago but there has been no comments. Is it now okay if I merge it? 

Description:
Add an OK box on what actions were taken. Choices are either A) N reciprocal associations created; B) no new associations created as they already exist; C) no associations exist so no reciprocal created.

----
In the average US hospital visit, there are more people involved in billing you than treating you.

Gary Griffin

**Comment by prculley** [comment]
I was a bit hesitant to merge it as @Nick-Hall was the original author of DNA and I don't understand what it was for or how to test it with the changes.

**Comment by Nick-Hall** [comment]
@prculley I'll take a look.

**Comment by GaryGriffin** [comment]
This change is not on the DNA gramplet but the SyncAssociation add-on. There is a slight relation in that SyncAssociation will create a reciprocal Association for DNA associations (as well as other types of Associations). For instance, it creates a reciprocal grandchild association for an existing grandfather association. There is a doc page for the SyncAssociation add-on at  https://gramps-project.org/wiki/index.php/Addon:SyncAssociation  - the last editor commented that there was no user feedback when executing, so I am requesting #410 to address that concern. 

The SyncAssociation add-on specifically addresses Nicks comment at https://sourceforge.net/p/gramps/mailman/message/32289573/ : “There is also nothing to stop you adding a second relationship which is the "reverse" of the first. It would be easy to write a tool to do this. “ 

The SyncAssociation add-on is that tool. It does write to the DB, so #408 (this initial checkin) should be reviewed, IMO. 


I have a major refactor for the DNA gramplet (does not write to DB) ready for testing. But I was hoping to merge this SyncAssociation change in before I submit that pull request (due to my lack of git knowledge, I can’t seem to create a separate branch for that change and don’t want them combined.)

I have created the doc for the revised DNA gramplet at my User page: https://gramps-project.org/wiki/index.php/User:GaryGriffin . I have not uploaded the images but the usage is there. The easiest way to describe it is that it does graphs like DNApainter — https://dnapainter.com/help/how-to-use . Once that PR is submitted, I will request Nick to review since he wrote the experimental version of this gramplet.

----
In the average US hospital visit, there are more people involved in billing you than treating you.

Gary Griffin

**Pull request merged**
