### PR TITLE
SyncAssociation OK dialog

### PR DESCRIPTION
**Pull request by GaryGriffin**
Add Ok Dialog for changes executed.

### CODE REVIEW

**Comment by PQYPLZXHGF** [comment]
Typically you don't merge this your self but leave it to the developers ( @Nick-Hall / @sam-m888 / @prculley etc...) who have rights to 
https://github.com/gramps-project/addons
so it can actually be rolled out to everyone eg: at the moment you have merged it but no one can see it!

**Comment by Nick-Hall** [comment]
It is OK to merge the change, but an [addon publisher](https://github.com/orgs/gramps-project/teams/addon-publishers/members) will also need to publish it.

**Comment by GaryGriffin** [comment]
I guess I am confused by the process. I submitted the SyncAssociation PR (with review requests for Nick and Paul) and waited a month but didn’t get any feedback. At that point, i thought that it was okay to merge since the last time I submitted a PR on this addon (again merged by mistake), I thought I was told to wait at least a week and then it was okay to merge. 

Is the issue that I submitted to maint51 and others dont see it until it is in master by a addon_publisher? I am pretty new to git.

Should I just assume I am not allowed to merge? That is fine, I just need to know how the PR gets reviewed and merged by someone at some point. 

I am working on the DNAgramplet right now and will have the same question. At this point I created the DNAgramplet PR and have announced it for testing. I have gotten good feedback and am incorporating those requests, closing my PR and creating a new PR with the updates.  I suspect I will be ready to have it reviewed for merge in a week or so.

**Comment by prculley** [comment]
The rules are not very well defined for addons...  So don't feel you are doing something wrong.  Ordinarily one of the developers will merge the PR and build/release the addon all at the same time.  In fact it is easier to do that as we don't have to sort out the already merged but unbuilt PRs to keep the build commits clean to a specific addon.

Until you are developing an addon that depends on changes made to Gramps master branch (different API or objects etc.) it is probably best to keep working in the current maintenance branch (gramps51).

I have been reluctant to merge anything changed related to the DNA Gramplet as that is Nick's code.  Don't want to step on any toes...  Same thing for Forms Gramplet.  While I don't see any DNA changes here, I thought that this was in some way related to that...

**Comment by GaryGriffin** [comment]
Thanks for the clarification.
SyncAssociation is indirectly related to the DNA gramplet in the sense that the DNA gramplet seems to be the first real usage of Associations. One of the earlier comments on the experimental DNA gramplet was that it did not create the reciprocal relationship. So first I created the SyncAssociation addon to do the reciprocal relation and now I am working on the DNA gramplet. I am also changing the name to DNA Segment Map gramplet since DNA seems too vague.

I will work on the maintt branch gramps51, And will not merge anything there. I dont want to bother people about reviewing so will add Nick as a reviewer for the upcoming DNA gramplet. 
 
----
In the average US hospital visit, there are more people involved in billing you than treating you.

Gary Griffin

**Pull request merged**
