### PR TITLE
[BirthdayGramplet]Add 'ignore birthday' functionality[gramps50]

### PR DESCRIPTION
**Pull request by Mattkmmr**
Birthdays of people tagged with a selected tag will be ignored by BirthdayGramplet if users wish to hide/ignore them.

### CODE REVIEW

**Comment by adamvazquez82** [comment]
https://gramps-project.org/wiki/index.php/BirthdaysGramplet

**Comment by Mattkmmr** [comment]
^ "Fix BirthdayGramplet" unfortunately I forgot an important line in my initial pull.

**Comment by wroldwiedbwe** [comment]
Works for me 👍 

config-ignore-tag-birthdaygramplet2
config-ignore-tag-birthdaygramplet

**Comment by sam-m888** [comment]
Thank you

**Comment by sam-m888** [comment]
- [ x] Support page updated to mention option.

**Comment by wroldwiedbwe** [comment]
@Mattkmmr How about the opposite of this eg: Only show birthdays for people with Tag?

**Pull request merged**
