### PR TITLE
bug 8437 and 8584 : ListEclair crash

### PR DESCRIPTION
**Pull request by SNoiraud**
Is it possible to add this to master, please.

### CODE REVIEW

**Comment by dsblank** [comment]
@romjerome You want to take a look at this, and merge the PR if ok?

**Comment by romjerome** [comment]
Note, it seems that I cannot add addons git repo(s) (github) from the web interface!

Can I commit into 'addons-source'?


--------------------------------------------
En date de : Mar 26.5.15, Doug Blank <notifications@github.com> a écrit :

 Objet: Re: [addons-source] bug 8437 and 8584 : ListEclair crash (#3)
 À: "gramps-project/addons-source" <addons-source@noreply.github.com>
 Cc: "romjerome" <romjerome@yahoo.fr>
 Date: Mardi 26 mai 2015, 17h54
 
 @romjerome You want to
 take a look at this, and merge the PR if ok?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by SNoiraud** [comment]
Could it be possible to have write access for jerome and me ?
In this case, I could avoid to use my fork.

**Comment by dsblank** [comment]
Of course, you just had to request it! You should have received a invitation/note.

**Pull request merged**
