### PR TITLE
Life line chart view

### PR DESCRIPTION
**Pull request by CWSchulze**
New view which shows individuals as lines in an ancestor or descendant chart. The length and position of the line depends on the actual life span and the marriages. The ancestor collapse is addressed. Labels for birth / names, death, and marriage can be added.
grafik

The selected person on the person tab is starting point in both charts. Birth/christening/baptism/death/burial/marriage dates need to be available to properly draw this chart.

Requirements:
- life_line_charts (svgwrite)

If you use msys2/x64 on windows you might use pacman to install pillow and dateutil:
```
pip3 install life_line_chart
```

Exemplary images:
grafik
grafik
grafik

Some general remarks
- The charts can be configured in the dialog:
    grafik
    grafik

- You may zoom (if the chart is focussed) with
    - "+" and "-"
    - Ctrl + mouse wheel
    - the GUI control buttons (+, -, fit to view, reset to 1)

- Scrolling is possible (if the chart is focussed) with
    - mouse wheel
    - Ctrl + left mouse button (grabbing)

- Siblings of ancestors can be shown in the ancestor chart:
    grafik
- Context menu enables editing, navigation, show/hide and showing siblings (only ancestor chart)
    grafik
- Persons i.e. the whole family branch can be hidden
- A tooltip shows the name, gramps id, birth and death date of the person.
    grafik

- Fotos of the persons can be displayed along the line. Their position is based on the date that is set in the media object.
- The diagram can be exported as SVG.
- You may also use the filter to fade out individuals:
    grafik

### CODE REVIEW

**Comment by adamvazquez82** [comment]
Hi @CWSchulze 
The screenshot looks enticing and I'd like to try this but only get the error below, initially with my family tree but then I realized it happens on an empty family tree :( 

>  Traceback (most recent call last):
>   File "C:\msys64\home\adamvazquez82\gramps/gramps/gui/viewmanager.py", line 809, in __create_page
>     page = page_def(pdata, self.dbstate, self.uistate)
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechartview.py", line 201, in __init__
>     'description': BaseGraph._formatting_description['family_shape']['short_description'],
> KeyError: 'family_shape'
> 

FYI to anyone testing this if you get

> 2020-05-04 00:20:41.928: WARNING: _manager.py: line 308: Plugin error (from 'lifelinechartview'): No module named 'life_line_chart'

You need to install that module from pip with 

`pip3 install life_line_chart`

**Comment by CWSchulze** [comment]
If the key 'family_shape' key is missing, then your life_line_chart version is outdated. Try
```pip3 install --upgrade life_line_chart```
I just released the latest changes, but since this flag has been added in version 1.2.11, your version seems to be older.

**Comment by adamvazquez82** [comment]
I have version '1.2.13'  should downgrade to the older version? How do I do that?

>>> dir(life_line_chart)

['AncestorGraph', 'AncestorGraphFamily', 'AncestorGraphIndividual', 'BaseFamily', 'BaseGraph', 'BaseIndividual', 'Exceptions', 'GedcomFamily', 'GedcomIndividual', 'GedcomParsing', 'InstanceContainer', 'LifeLineChartCannotMoveIndividual', 'LifeLineChartCollisionDetected', 'ReadGedcom', 'SimpleSVGItems', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'ancestor_graph_family', 'ancestor_graph_individual', 'estimate_birth_date', 'estimate_death_date', 'estimate_marriage_date', 'get_date_dict_from_tag', 'get_gedcom_instance_container']

>>> life_line_chart.__version__
'1.2.13'


> 10776: ERROR: grampsapp.py: line 156: Unhandled exception
> Traceback (most recent call last):
>   File "C:\msys64\home\me\gramps/gramps/gui/viewmanager.py", line 871, in view_changed
>     self.__change_page(page_num)
>   File "C:\msys64\home\me\gramps/gramps/gui/viewmanager.py", line 885, in __change_page
>     self.active_page.set_active()
>   File "C:\msys64\home\me\gramps/gramps/gui/views/navigationview.py", line 153, in set_active
>     PageView.set_active(self)
>   File "C:\msys64\home\me\gramps/gramps/gui/views/pageview.py", line 335, in set_active
>     self.build_tree()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechartview.py", line 423, in build_tree
>     self.update()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechartview.py", line 463, in update
>     self.main()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 1641, in main
>     self.lifeline.draw()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 1040, in draw
>     size_w_a = int(graph.get_full_width()*self.zoom_level)
> AttributeError: 'NoneType' object has no attribute 'get_full_width'
>

**Comment by CWSchulze** [comment]
No, the newest is fine. I'll try to remove all my settings to reproduce your problem.

```AttributeError: 'NoneType' object has no attribute 'get_full_width'```
It seems this error occurrs, if no person is selected. Is that possible If you have a non-empty database?

**Comment by CWSchulze** [comment]
This error should be handled now

**Comment by adamvazquez82** [comment]
Thanks for the update 👍  I downloaded new version with fix and created an empty family tree and then went to your view and get the following:

> 25121: ERROR: grampsapp.py: line 156: Unhandled exception
> Traceback (most recent call last):
>   File "C:\msys64\home\adamvazquez82\gramps/gramps/gui/viewmanager.py", line 871, in view_changed
>     self.__change_page(page_num)
>   File "C:\msys64\home\adamvazquez82\gramps/gramps/gui/viewmanager.py", line 885, in __change_page
>     self.active_page.set_active()
>   File "C:\msys64\home\adamvazquez82\gramps/gramps/gui/views/navigationview.py", line 153, in set_active
>     PageView.set_active(self)
>   File "C:\msys64\home\adamvazquez82\gramps/gramps/gui/views/pageview.py", line 335, in set_active
>     self.build_tree()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechartview.py", line 423, in build_tree
>     self.update()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechartview.py", line 463, in update
>     self.main()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 1645, in main
>     self.lifeline.set_values(root_person_handle, self.maxgen, self.background,
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 1016, in set_values
>     plot()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 979, in plot
>     root_individual = self.life_line_chart_ancestor_graph._instances[(
>   File "C:/msys64/mingw64/lib/python3.8/site-packages/life_line_chart/InstanceContainer.py", line 54, in __getitem__
>     self._data[key] = self._individual_constructor(self, key)
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 272, in <lambda>
>     lambda self, key: GrampsIndividual(self, dbstate, key[1]),
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 128, in __init__
>     self._gramps_person = self._dbstate.db.get_person_from_handle(
>   File "C:\msys64\home\adamvazquez82\gramps/gramps/gen/db/generic.py", line 1282, in get_person_from_handle
>     return self._get_from_handle(PERSON_KEY, Person, handle)
>   File "C:\msys64\home\adamvazquez82\gramps/gramps/gen/db/generic.py", line 1265, in _get_from_handle
>     raise HandleError('Handle is empty')
> gramps.gen.errors.HandleError: Handle is empty
> 

**and when I attempt to close the error assistant**
lifeissue error

**I get**

> (Gramps.py:11380): Gtk-CRITICAL **: 18:51:47.202: gtk_widget_set_size_request: assertion 'width >= -1' failed
> Warning: DbState: Exception occurred in callback function.
> Traceback (most recent call last):
>   File "C:\msys64\home\adamvazquez82\gramps/gramps/gen/utils/callback.py", line 405, in emit
>     fn(*args)
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechartview.py", line 453, in change_db
>     self.update()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechartview.py", line 463, in update
>     self.main()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 1651, in main
>     self.lifeline.draw()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 1057, in draw
>     self.surface = cairo.ImageSurface(cairo.FORMAT_ARGB32,
> cairo.Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
> 



So far all my test have been done on empty family tree because if it can't handle that then I won't let it near my normal family tree.

**Comment by adamvazquez82** [comment]
With new fix 

> 
> 21859: ERROR: grampsapp.py: line 156: Unhandled exception
> Traceback (most recent call last):
>   File "C:\msys64\home\adamvazquez82\gramps/gramps/gui/viewmanager.py", line 871, in view_changed
>     self.__change_page(page_num)
>   File "C:\msys64\home\adamvazquez82\gramps/gramps/gui/viewmanager.py", line 885, in __change_page
>     self.active_page.set_active()
>   File "C:\msys64\home\adamvazquez82\gramps/gramps/gui/views/navigationview.py", line 153, in set_active
>     PageView.set_active(self)
>   File "C:\msys64\home\adamvazquez82\gramps/gramps/gui/views/pageview.py", line 335, in set_active
>     self.build_tree()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechartview.py", line 423, in build_tree
>     self.update()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechartview.py", line 463, in update
>     self.main()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 1657, in main
>     self.lifeline.draw()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 1086, in draw
>     for key, value in self.life_line_chart_ancestor_graph.additional_graphical_items.items():
> AttributeError: 'AncestorGraph' object has no attribute 'additional_graphical_items'
>

**Comment by CWSchulze** [comment]
It would be nice to get this running on your database. I added an additional check for missing root person and image sizes. But I think the actual problem is, that I cannot access your root person. This bugfix should only handle this problem by showing an empty chart. You should try this with a non-empty database. It doesn't not write anything to the database, or send its content somewhere else. However, If you don't trust that plugin, you could use one of the test databases in gramps.

I now tested an empty chart, and a chart with one newly added individual (with birth and death date).

Maybe I don't fully understand all variants of gramps databases. But empty databases are not handled well. This view assumes that you 
1. have a database
2. have selected a person
    grafik
3. that person has ancestors which are also visible in other charts:
    grafik

Then you should basically get the same information as in the default view:
grafik

**Comment by adamvazquez82** [comment]
Looks really good :)

Empty family trees handled 👍  , should you still be able to save a chart if the family tree is empty, also can the filename be given an extension of **svg** automatically?

Using example.gramps this time.https://gramps-project.org/wiki/index.php?title=Example.gramps

When chart load can we set it by default(or have option) to use the whole horizontal canvas?

Tried making the chart really really large by pressing "+" and get this error.

> 43194: ERROR: grampsapp.py: line 156: Unhandled exception
> Traceback (most recent call last):
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 659, in on_key_press
>     self.draw()
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 1168, in draw
>     text_function(
>   File "C:\Users\adamvazquez82\Documents\gramps/gramps51/plugins/LifeLineChartView/lifelinechart.py", line 1135, in text_function
>     ctx.show_text(line)
> cairo.Error: error occurred in the Windows Graphics Device Interface
> 
> 

Had to delete all the "Ancestry_lifelinechartview_*.ini" files to get back to default size.  When I try increasing the size then attempt to decrease the size it does not respond for me all the time?


Have you seen the canvas control icons in GraphView?
https://gramps-project.org/wiki/index.php/Graph_View


In the configuration is the setting "Birth label alogn path" a spelling error, is the word "alogn" meant to be "align" or "along"?

test lifeline

**Comment by CWSchulze** [comment]
Yes, my GTK skills are poor.

I have no idea how the file save dialog should look like in GTK. I saw one implementation in Gramps with a combobox. Obviously the current impelmentation only filters the visible files. I'm also missing typical windows hotkeys like backspace/alt+left/alt+right/F5. Do you have to implement all this manually?

My first approach to implement zooming was to enlarge the canvas and use the original scroll implementation. That seems to be a bad idea. I guess I have to reactivate the xy-offset and keep the canvas at the window size.

I failed to install the GraphView, so i haven't seen the icons yet.

Exporting empty svg? Never tried this. Just looked into this. You can update life_line_chart module.

I thought about automatic fitting into the visible area, or keeping the size constant. But I realized that I prefer to define the line layout (width and font size). Every graph would have a different line width and font size if you change to total width.

**Comment by CWSchulze** [comment]
The file save dialog now adds the ".svg" if it is missing, and doesn't accept if it is not .svg or empty.

The render efficiency is improved, zooming reimplemented (wheel/ctrl/shift), controls were added. I did not use goocanvas.

**Comment by johnbickmore** [comment]
Hi @CWSchulze , thanks for this wonderful view. 🥇 

Initially I only had the following unhelpful error

faillifelines
and almost emailed you ;) Can I suggest you test for the requirement and pop up a message like Graphview does see https://github.com/gramps-project/addons-source/blob/master/GraphView/graphview.gpr.py for how they do it.

Once I added the requirements it worked but one issue I have and I'm not sure if it's only me but when the chart is larger than screen I'm unable to scroll up or down the chart, note that my mouse does not have a scroll wheel it is a normal mouse.

I looked but does the chart have an option display horizontally  so I don't have to bend my head to read the labels?

**Comment by CWSchulze** [comment]
Thanks.

The import now has better error messages:
grafik
grafik

I wouldn't call it "normal" if your mouse doesn't have a wheel ;-)
However, you can move the view by pressing Ctrl and the left mouse button. I now changed the mouse cursor to make this more visible (you still have to click on the view first to focus it).

I added more options to configure the labels:
grafik

A new icon is used for the button:
grafik

Debug messages... well the optimization of the whole graph (compressing and flipping) is still inefficient and buggy. I now deactivated the messages by default. I also deactivated the optimization. So it should be much faster now, and if something fails the chart doesn't look nice.

**Comment by wroldwiedbwe** [comment]
Lovely chart, thank you for creating it, 

fyi in your screenshot of the "error messages" it shows 

> "To dismiss all future **Graphview** warning click Dismiss.

You might want to change it to 

> To dismiss all future **Life Line Chart** warning click Dismiss.

**Comment by CWSchulze** [comment]
@wroldwiedbwe Thanks, fixed it.

I added a new feature. If the images (png/jpeg) of the person are available in the gramps db (gallery), then they can be displayed in the chart.
grafik
If the date information of the media object is set, they will also be shown at the right place.

Maybe some kind of filter might be required to choose the images.

**Comment by wroldwiedbwe** [comment]
Keeps on getting better 👍 

new context menu and double years on side

Should I be seeing the double years on the right?

**Comment by CWSchulze** [comment]
The idea was to show the actual content which will also be exported to svg. On the right I just wanted to have a more readable version which is always visible. The font size is limited on the right. E.g. here:
grafik
Or somewhere in the center of the chart:
grafik

But if this is not intuitive to the user, maybe I should remove the year numbers from the main drawing area. Maybe I should at least separate the two drawing areas from each other...

**Comment by wroldwiedbwe** [comment]
Yeah removal of the second years is probably good idea if the years don't align or the lines don't match.

Noticed another issue when I start from the Gramps AIO on windowsat the command line  I get the following

> ERROR: Failed reading plugin registration lifelinechartview.gpr.py
> Traceback (most recent call last):
>   File "C:\Program Files\GrampsAIO64-5.1.2\gramps\gen\plug\_pluginreg.py", line 1196, in scan_dir
>     make_environment(_=local_gettext), {'uistate': uistate})
>   File "lifelinechartview.gpr.py", line 66, in <module>
> NameError: name 'version_required' is not defined
>

**Comment by CWSchulze** [comment]
I fixed the error handling during import. The life_line_chart module doesn't seem to be available. The error message mentioned above now works properly again.

I haven't tried the AIO yet. Is this build locally? Where do you have to add additional modules?

**Comment by prculley** [comment]
The Windows AIO doesn't support adding additional prerequisites by the user.  Which is why I suggested trying to reduce the number of (large [numpy]) prerequisites in my earlier comment.  If this addon proves popular, I may add the necessary smaller prerequisites to the AIO when I next create one.

Note; if any of the prerequisites are pure Python, it may be possible to include them with the addon...

**Comment by CWSchulze** [comment]
the requirements numpy, svgpathtools, pillow and dateutil are no longer required to use the life_line_chart module in gramps. svgwrite is required, but seems to be written in python. There should be no more binary dependency.

@prculley: Do you mean adding the module folders to the source folder of this gramps addon? Is there another specific place?

**Comment by CWSchulze** [comment]
@wroldwiedbwe : I added a frame around the charts and only show years in the axis drawing:
grafik

**Comment by wroldwiedbwe** [comment]
>  I added a frame around the charts and only show years in the axis drawing:

Much clearer 👍 

If you don't have the life_line_chart module this prints on the command line

> 2020-05-21 10:29:04.604: WARNING: lifelinechartview.gpr.py: line 90:
> 
> Life Line Chart failed to import life_line_chart module:
> <i>No module named 'life_line_chart'</i>
> 
> Please install life_line_chart module:
> <i>pip install life_line_chart==1.2.28</i>

The html  italic tags probably should not be there when printing to the command line.

Also with the new add to blacklist wording maybe rename it to "Hide person" / "Show Person"?

>> Note; if any of the prerequisites are pure Python, it may be possible to include them with the addon...

@prculley  That's a bad idea you are proposing; keep the addon-source code purely that otherwise the Linux distributions will crack it. Possibly the only module that could be included would be @CWSchulze   [life_line_chart ](https://github.com/CWSchulze/life_line_chart) module but that maybe an issue as it is licensed under [MIT](https://github.com/CWSchulze/life_line_chart/blob/master/LICENSE)  and not GPL2 like all the code in the addon-source repository. So technically only if the code is re-licensed if even possible!

**Comment by CWSchulze** [comment]
I just tested it. I need to 
* copy "life_line_chart" and "svgwrite" to the addon folder
* add the addon folder to the path environment
* replace or remove "cmath" module (which doesn't seem to be included in aio)

I would be possible to download the libraries and place them there - so much for the license.
However, to replace cmath i need an implementation of Cardano's equation which does not rely on cmath, numpy or something like that.
Maybe the path environment could be avoided by using importlib.

**Comment by CWSchulze** [comment]
I found a nice solution that works on msys2 and the most recent aio installer. I download missing modules (svgwrite and life_line_chart). It is stored in the user plugins path. Maybe somebody could test it under linux? So no changes are required to the aio installer.
grafik
grafik


From a license point of view, I think it is fine, since the code is not part of gramps, and only downloaded if the user agrees.
MIT license allows to use the code in commercial and open source project. So even if the code is committed to the gramps project, I don't see a problem.

**Comment by prculley** [comment]
If the prerequisites are pure Python, and downloaded to the users plugins path (presumably this addon) there should be no conflict with other installed versions.  Particularly if you don't download if the prerequisites are already present.  Nice thinking outside the box.  I agree about the licensing, but I'm not a lawyer (thank the gods).

**Comment by wroldwiedbwe** [comment]
Great work around 🥇    

Love the additional chart view.

**Comment by johnbickmore** [comment]
lldc-toolbar

> I found a nice solution that works on msys2 and the most recent aio installer. I download missing modules (svgwrite and life_line_chart). It is stored in the user plugins path.

Excellent works with my Gramps AIO, Thank you 👍 

A few suggestions to help wrap this up are to [create a support page](https://gramps-project.org/wiki/index.php/Addons_development#List_and_document_your_addon_on_the_wiki) on the Gramps wiki and add an **"About Life line Chart Views"** context menu that goes to the link ([like Graphview](https://gramps-project.org/wiki/images/9/9a/Graph_View_Empty_context_menu.png))
Graph_View_Empty_context_menu

and/or add a  help button to lifelines addons toolbar

llac-toolbar

similar to how @vantu5z has in PR https://github.com/gramps-project/addons-source/pull/343 .

Has anyone tested it on MacOS?

**Comment by CWSchulze** [comment]
I worked on the german translation. I had some issues with having the same config file and settings for two views. Now they use the same settings. Tooltip now also works in the descendant chart.

Is there a reason that the smooth scrolling doesn't work with the aio version?

The help button is included, but I'm working to get my wiki account.
grafik

I haven't done any tests on Mac yet.

**Comment by adamvazquez82** [comment]
> Is there a reason that the smooth scrolling doesn't work with the aio version?

Can you describe what you mean, Maybe it depends on your computers Graphic Card, I don't see any issue myself.

By the way nice work around on downloading your module from the addon itself 👍 

> The help button is included, but I'm working to get my wiki account.

https://gramps-project.org/wiki/index.php/Life_Line_Chart_View

Button works and goes to your wiki page successfully, too many words on the help button maybe change to just a question mark (?) or the word "help" or the help icon like:

windows-8-help-icon_398639



What is left to be done, before everyone can see your great work?

**Comment by CWSchulze** [comment]
I think this ready to be merged. Maybe one change could be merged before that (replaced tooltip by label). And the help button, yes.


Just like graphview I used the gtk stock icons, which are ... not pretty? The help icon turned out to be a lifebelt, which i find not helpfull.
grafik ->[https://developer.gnome.org/gtk2/stable/gtk2-Stock-Items.html#GTK-STOCK-HELP:CAPS](link)
I also wasn't sure if it is obvious, that a help button at that place opens the help for the life line charts. People might expect that it opens the general gramps help. Is that obvious to you? That was the reason to add the addon title to the help button. Are there any other icon collections used in gramps? I'm open to change all of the icons, I just tried to stick to the gramps "look and feel".

Normal scrolling triggers movement by a fixed distance. Only the frequency may change, but acceleration etc. are not supported and the maximum speed is pretty low. Smooth scrolling enables scrolling in both directions and with highly variable speed. Browsers usually support this under windows. Basically this works if i don't use the aio version. If it works for you, maybe this is a problem with my installation.
Instead of a simple "move up or down" event, Gtk provides a "move smoothly" event with a step size. (-> ```Gdk.EventMask.SMOOTH_SCROLL_MASK```, ```hasdeltas, dx, dy = event.get_scroll_deltas()```)
A simple way to test if it is active is to check if it switches to left-right scrolling if you press shift. If it does, it is not smooth scrolling.

Meanwhile I have revised the underlying algorithms. I have >100 commits which are not yet pushed into the life_line_chart module on github. But from a users perspective almost nothing changes. Its mainly about simplifying, documenting, efficiency, debugging, handling of special cases, and preparing some extensions. Also the optimization is improved. So soon there will be an update, but I don't know when, and after that there will be the next update... doesn't make sense to wait for that.

The most striking change I have done to the gramps addon, is replacing the tooltip by a label which is updated instantly (I'm too impatient to wait for the tooltip). Maybe this is an improvement which should be added now.
grafik

**Comment by CWSchulze** [comment]
Done.

New button layout:
grafik
from [here](https://icons8.com/icons/ios)

I failed to fix the smooth scrolling. I don't think that's related to my addon.
The only code in gramps referring to smooth scrolling is the selectionwidget, and that's a void implementation. It should use the mentioned ```get_scroll_deltas``` not just us the sign as direction indicator (selectionwidget.py):
```
...
        if event.direction == Gdk.ScrollDirection.UP:
            self.zoom_in()
        elif event.direction == Gdk.ScrollDirection.DOWN:
            self.zoom_out()
        elif event.direction == Gdk.ScrollDirection.SMOOTH:
            if event.delta_y < 0:
                self.zoom_in()
            else:
                self.zoom_out()
...
```

**Comment by CWSchulze** [comment]
By the way, what is the usual procedure to update the addon? Who has the rights and is willing to approve the pull requests?

**Comment by CWSchulze** [comment]
About to change the icons again... the license is a pain...

**Comment by prculley** [comment]
> 
> 
> By the way, what is the usual procedure to update the addon? Who has the rights and is willing to approve the pull requests?

I look at the PRs periodically, if the 'Work in Progress' flag is off and no new commits have occurred for 10 days or so, then I will try to test the PR myself.  If all is well, I usually accept and build/release.  Note for a few addons, (Forms, for example) I let the original author review and accept, as the author is more likely to know what is going on.  Several of us developers have the rights, but lately only myself, Nick Hall and Sam Manzi have been doing it.

**Comment by wroldwiedbwe** [comment]
Works for me 👍 

new icon

**Comment by CWSchulze** [comment]
Some changes:
- Reset button for placement/selection (i.e. hidden persons, modified placement, shown children)
- interactive highlighting individuals/families (mouse hover)
- manual modification of placement if pedigree collapse causes ambiguities (context menu)
- added family information to context menu
- ancestors are placed by default above the first marriage of the oldest child
- optional pedigree collapse handling
- optional vertical mirroring
- optional coloring based on last name (persons with the same last name share a color)
- info label with mouse position as date
- improved sorting graphical items into layers (e.g. images are always above lines, cross chart connections are placed behind other life lines, text top-most)

grafik
grafik

**Comment by CWSchulze** [comment]
@prculley it would be nice, if you could merge this.

**Comment by adamvazquez82** [comment]
Umm prculley mentioned:

> I look at the PRs periodically, if the 'Work in Progress' flag is off and no new commits have occurred for 10 days or so, then I will try to test the PR myself. 

So at a minimum ten days after your last change to give everyone a chance to test. 

I'll download and test the new version.

Looking forward to telling people about this addon 👍

**Comment by CWSchulze** [comment]
Hmm. I will stop updating the addon to realize this moratorium.

**Comment by CWSchulze** [comment]
I could merge the changes from https://github.com/CWSchulze/addons-source/tree/LifeLineChartView_next_update
This update is also unchanged since 3 weeks.

**Pull request merged**
