### PR TITLE
PlaceTool gramplet

### PR DESCRIPTION
**Pull request by kkujansuu**
This is a gramplet that helps to manage multiple places at the same time. See README.

### CODE REVIEW

**Comment by wroldwiedbwe** [comment]
Travis ci found a bunch of trailing white spaces see : https://travis-ci.org/gramps-project/addons-source/builds/639056699#L2423

**Comment by wroldwiedbwe** [comment]
Found the https://github.com/kkujansuu/addons-source/blob/maintenance/gramps51/PlaceTool/README.md !!

Gramplet to change properties of multiple places at the same time. The properties that can be changed are:

*  place type
*  tag
*  enclosing place

PlaceTool UI

**Comment by Nick-Hall** [comment]
I think that this will be useful.  A few suggestions:

* Change the name to something like PlaceUpdate.  It is a gramplet not a tool.
* Use bold for headings only, not for field labels.
* Use a standard place selector for the enclosing place to make it consistent with other parts of Gramps.

**Comment by wroldwiedbwe** [comment]
Thanks, Travis ci found one more trailing white space see : https://travis-ci.org/gramps-project/addons-source/builds/639216629#L2403

**Pull request merged**
