### PR TITLE
Initial commit for Swedish webconnectpack

### PR DESCRIPTION
**Pull request by pehlm**
Swedish WebConnectPack, it seems to work good on my computer. Please test!

### CODE REVIEW

**Comment by pehlm** [comment]
Thank you for merging the plugin!
Is there a reason why you did not include lines 36 (Geneanet) and 39 (WikiTree) in SVWebPack.py in template.po? They are missing.
Thank you!

**Comment by prculley** [comment]
The template is automatically generated by the script to release.  If you look at your source code, I don't think those two words are marked for translation.

**Comment by pehlm** [comment]
Yes, as I said, I saw it now. Has changed a bit in the Swedish translation file so it is similar to the template. Thank you.

**Comment by RogerDodger8989** [comment]
Any news on this?

**Pull request merged**
