### PR TITLE
[GraphView] add custom avatars

### PR DESCRIPTION
**Pull request by vantu5z**
Inspirit by Brian ideas (send me email with avatar included).

Add presets for avatars and allow user to set it from own files.
Styles:
- Custom
- Dark (default)
- Light
- Cartoon

Avatar support can be extended to show different avatars depending on person attributes (not only gender).

### CODE REVIEW

**Comment by emyoulation** [comment]
Several people have asked about illustrating graphs in the way described:
"Avatar support can be extended to show different avatars depending on person attributes (not only gender). "
Currently, they can do this by showing Tags. But the meaning is not intuitive... there has to be a color key to lookup what 'purple' or 'orange' means.

An example might be that they want to use a 'boat' avatar for anyone with an "immigration" event. Or a specific Attribute value.

How could the Avatar option be implemented?

(If the Avatar modification is complex, I can see a viable alternative of writing a SuperScript that inserts a particular media object at the beginning of their Gallery.)

**Comment by vantu5z** [comment]
@emyoulation Do you mean something like this #477. It's not finished for now and I have no time to make it done.

**Comment by emyoulation** [comment]
That looks cool!

Do you mind if I point it out to Chris Horn? It looks like something that fit nicely into his CardView.

**Comment by vantu5z** [comment]
Why not, if this help to make Grams better.

**Pull request merged**
