### PR TITLE
Added GeoTimeLines plugin

### PR DESCRIPTION
**Pull request by tbmapman**
Initial upload for my GeoTimeLines plugin.

### CODE REVIEW

**Comment by PQYPLZXHGF** [comment]
Welcome looks good,

Usually the idea of Pull request is to allow people to test the addon and allow feedback; then getting somebody not yourself to merge it!  

GPL License sections missing please add them.

Anyway feeling grumpy don't take it personally, second one in less that week!

**Comment by Call-Me-Dave** [comment]
2024-09-28 16_24_12-Example Gramps - GeoTimeLines - Gramps
2024-09-28 16_23_26-Example Gramps - GeoTimeLines - Gramps
2024-09-28 16_23_08-Example Gramps - GeoPerson - Gramps
2024-09-28 16_25_51-Mozilla Firefox

**Comment by tbmapman** [comment]
> Usually the idea of Pull request is to allow people to test the addon and allow feedback; then getting somebody not yourself to merge it!

Ok, sorry about that and will do in the future! I wasn't sure if the pull request was because I pushed it wrong using git on my end or not.

> GPL License sections missing please add them.

I'll add them later today.

>Tool tip for the view shows "TimeLines Map" without spaces between the words and the configuration tab shows "GeoTimeLines options" suggest deciding on one name for the addon please? (Also noticed this PR is called "Added GeoTimeLines plugin" so it looks like you might prefer something like "Geography Time Lines"?

"GeoTimeLines" was the Python name I was used to looking at, and "TimeLines Map" was the formal name (I was trying to follow the convention I saw on the "GeoAncestors"/"Ancestors Map" plugin). I'll look over and standardize every name seen to the user as "TimeLines Map". (TimeLines as a wordplay between "timeline", and "time" and "lines").

>Note the sudden popup on switching was unexpected and not in keeping with the rest of the Geography views , default should be active person like the rest of Gramps!
> 
>In "GeoTimeLines options" tab please change "Active Individual" to "Active Person" to match the rest of Gramps see the [glossary](https://gramps-project.org/wiki/index.php?title=Gramps_Glossary#A)

I'll fix them later today.

>Hope you don't mind the feed back, I really like the view

Not at all! Thanks!

**Comment by GaryGriffin** [comment]
My suggestion is you create a new PR to address issues found (but do not merge). Maybe add a tag that it is WIP, so it is not merged. Keep adding commits on that PR until all are resolved. When it is ready for merge (and publishing) remove the tag and someone can merge the PR and then publish. 

This is a very interesting view. Great work. 

I put 2 bugs in the Discourse discussion since I didn't know whether you were ready for Mantis bug reports (and that it is not yet published).

**Comment by emyoulation** [comment]
The Discourse discussion thread is at:  https://gramps.discourse.group/t/timelines-map-addon-beta-testing/6130

**Comment by emyoulation** [comment]
Thomas and Gary,

Perhaps the `GeoTimeLines.gpr.py` registration could be changed during the testing phase:

```
    status=BETA.
    audience = EXPERT,
    help_url="https://gramps.discourse.group/t/timelines-map-addon-beta-testing/6130/7";
```

**Comment by Call-Me-Dave** [comment]
https://github.com/gramps-project/addons-source/pull/608

**Pull request merged**
