### PR TITLE
Add detailed descendant report with images

### PR DESCRIPTION
**Pull request by jpschewe**
This report is based on the detailed descendant report and has been modified to display as many images as possible.

### CODE REVIEW

**Comment by sam-m888** [comment]
@jpschewe Thank you for the new report. 👍 

Unfortunately my first attempt at running the report using the default testing family tree [example.gramps](https://gramps-project.org/wiki/index.php?title=Example.gramps) shows the following error:

> 2017-11-18 09:53:39.800: ERROR: _reportdialog.py: line 735: Failed to run report.
> Traceback (most recent call last):
>   File "/home/gramps/gramps/gui/plug/report/_reportdialog.py", line 699, in report
>     MyReport.write_report()
>   File "/home/sam/.gramps/gramps42/plugins/DetDescendantReport-images/detdescendantreporti.py", line 321, in write_report
>     self.write_person(key)
>   File "/home/sam/.gramps/gramps42/plugins/DetDescendantReport-images/detdescendantreporti.py", line 417, in write_person
>     self.write_person_info(person)
>   File "/home/sam/.gramps/gramps42/plugins/DetDescendantReport-images/detdescendantreporti.py", line 752, in write_person_info
>     self.write_images(person.get_media_list())
>   File "/home/sam/.gramps/gramps42/plugins/DetDescendantReport-images/detdescendantreporti.py", line 976, in write_images
>     media_ref.get_attribute_list() )
>   File "/home/sam/.gramps/gramps42/plugins/DetDescendantReport-images/detdescendantreporti.py", line 923, in do_attributes
>     endnotes = self._cite_endnote(attr)
> AttributeError: 'DetailedDescendantReportI' object has no attribute '_cite_endnote'
>

**Comment by sam-m888** [comment]
Note that you have included another DetDescendantReport-images/**.gitignore**  file instead of updating the existing [.gitignore](https://github.com/gramps-project/addons-source/blob/maintenance/gramps42/.gitignore) file which from a quick check already covers the two rules you have listed, so I suggest you remove it please.

**Comment by jpschewe** [comment]
@sam-m888 What version of gramps are you testing with? I'm using 4.2.5 that is installed on my system. I tried loading the example tree as you suggested and the only errors I get are about loading images that don't exist.

**Comment by jpschewe** [comment]
@sam-m888 I have now reproduced the problem. I will debug this and update the branch.

**Comment by jpschewe** [comment]
@sam-m888 OK, I've pushed the changes and tested the report with the example tree using different include options to ensure that the report doesn't have other hidden issues based on what is selected for output.

**Comment by sam-m888** [comment]
Apologies for not being more specific with my testing results.

The error occurred as you have found out after I selected all the checkboxes on the reports "include" tab.

> @sam-m888 What version of gramps are you testing with?

Using the up to date gramps42 branch which may become gramps 4.2.7 

> @sam-m888 OK, I've pushed the changes and tested the report with the example tree 

Thank you.

Tested the report it works 👍 

Side by side comparison (original report versus new)
side_by_side_comparison


Existing report versus new report include dialog


existing-report-versus_new_report_include_dialog

**Comment by sam-m888** [comment]
Observations

My first attempt only generated an identical report to the original DDR report,  can I suggest that as you title the report as including all images that the default for your report is that "include photo/images from gallery" be checked by default. 

I also note an additional checkbox option selected by default for "include todo notes" not mentioned in your summary.


```
+# Copyright (C) 2017      Jon Schewe <jpschewe@mtu.net> - modifications to add all images
+#
+# This report is a modification of the detailed descendant report. It has
+# been modified to include as many images as possible. This is useful for
+# creating a report showing all pictures of people as well as sources and
+# citations.


+        inctodo       - Whether to include todo notes.

+        Write out all images in media_list as a table.
+        This is based on the code from the individual report.


+        Write all the entries in the bibliography as endnotes with the media.
+        This is copied from endnotes.py and modified to include media.
```

**Comment by jpschewe** [comment]
Those are good suggestions. I've added those changes. Are there other suggestions?

This is my first contribution to gramps, so I'm looking for suggestions on how to improve my contribution.

**Comment by sam-m888** [comment]
> Those are good suggestions. I've added those changes. Are there other suggestions?

Your welcome, no more suggestions on this PR, I'll merge this PR and build the addon making it available to Gramps 4.2.x users.

Thank you for your first contribution 👍

**Comment by sam-m888** [comment]
> Are there other suggestions?

Create an [addon page](https://gramps-project.org/wiki/index.php?title=Addons_development#List_and_document_your_addon_on_the_wiki) on the wiki that shows usage with an example of the todo list (with screenshots)  

If you need me to create the initial page please ask.

**Comment by jpschewe** [comment]
If you could create an initial page with an example template that would be great.

My wiki account is currently pending.

Do I need to upload a tar.gz file to the addons repository as well? I see that under "Package your addon".

**Pull request merged**
