### PR TITLE
[PhotoTaggingGramplet] add age column[gramps51]

### PR DESCRIPTION
**Pull request by vantu5z**
Resolve feature request [#11065](https://gramps-project.org/bugs/view.php?id=11065)

### CODE REVIEW

**Comment by sam-m888** [comment]
Testing again an came across the following error, attempting to work out how to recreate.

> ./Gramps.py 
> Warning: History: Exception occurred in callback function.
> Traceback (most recent call last):
>   File "/home/grampsdev/aaSandbox/gramps/gramps/gen/utils/callback.py", line 405, in emit
>     fn(*args)
>   File "/home/grampsdev/aaSandbox/gramps/gramps/gen/plug/_gramplet.py", line 309, in update
>     self._generator = self.main()
>   File "/home/grampsdev/.gramps/gramps50/plugins/PhotoTaggingGramplet/PhotoTaggingGramplet.py", line 499, in main
>     self.load_image(media)
>   File "/home/grampsdev/.gramps/gramps50/plugins/PhotoTaggingGramplet/PhotoTaggingGramplet.py", line 514, in load_image
>     self.retrieve_backrefs()
>   File "/home/grampsdev/.gramps/gramps50/plugins/PhotoTaggingGramplet/PhotoTaggingGramplet.py", line 534, in retrieve_backrefs
>     coords = self.selection_widget.proportional_to_real_rect(rect)
>   File "/home/grampsdev/aaSandbox/gramps/gramps/gui/widgets/selectionwidget.py", line 355, in proportional_to_real_rect
>     return (self._proportional_to_real((x1, y1)) +
>   File "/home/grampsdev/aaSandbox/gramps/gramps/gui/widgets/selectionwidget.py", line 482, in _proportional_to_real
>     w, h = self.original_image_size
> AttributeError: 'SelectionWidget' object has no attribute 'original_image_size'

**Comment by sam-m888** [comment]
Example showing age column.

phototagginggramplet-with-age-column

**Comment by sam-m888** [comment]
Suggestion possibly not show the word "dead" as that is a status and 'deceased' is the proper word.

**Comment by vantu5z** [comment]
May be. I added this to distinguish alive and dead, because it's not clear.
I added it as mark (status) but not in separate column. Maybe make it as free style text "dead in AGE age". Sorry for my English, believe you correct me  if needed. :)

**Comment by sam-m888** [comment]
> Maybe make it as free style text "dead in AGE age". 

I agree free style text in that form would be clearer, can you change it to read:

"Dead at {AGE} age" 

> Sorry for my English, believe you correct me if needed. :)

Your English is great compared to me speaking your native Language :)

Thanks for your patience.

**Comment by vantu5z** [comment]
Change string for age column.
And rebase for gramps51

**Comment by sam-m888** [comment]
Thank you

**Comment by sam-m888** [comment]
- [x] Update image for documentation ( https://gramps-project.org/wiki/index.php/Photo_Tagging_Gramplet )

Photo-Tagging-example-51

**Pull request merged**
