### PR TITLE
Change BetaWhatsNext to Beta, add verbose and debug options

### PR DESCRIPTION
**Pull request by GaryGriffin**
the .gpr.py changed to "BETA" status and re-target my repository for the help_url

The main module as several changes:
- added 2 new options: a (partially implemented) verbose suggestion, and; a debug (they will eventually be GUI options)
- added another check for meeting the missing data quota (check at each descendant rather than each completed generation)
- re-format for Black compliance

### CODE REVIEW

**Comment by GaryGriffin** [comment]
Updated per BAM request

**Comment by emyoulation** [comment]
Thank you for posting the Pull Request.  I _will_ figure out using GitHub Desktop at some point!

**Review by emyoulation — APPROVED** [review]
Verified the downloaded files create a working gramplet with 5.2.1

Please post

**Comment by emyoulation** [comment]
thank you!

    On Friday, September 27, 2024 at 12:41:55 PM CDT, GaryGriffin ***@***.***> wrote:  
 
 


Merged #606 into maintenance/gramps52.

**Pull request merged**
