### PR TITLE
[GraphView] Fix all-connected feature and search

### PR DESCRIPTION
**Pull request by vantu5z**
Fixes for Graphview issues:
- [12220](https://gramps-project.org/bugs/view.php?id=12220) (search)
  Use `Glib.idle_add` instead of `multiprocessing`.
- [12222](https://gramps-project.org/bugs/view.php?id=12222) (instances)
  Fixed by 12220.
- [12225](https://gramps-project.org/bugs/view.php?id=12225) (all-connected recursion exception)
  Rewrite building all-connected graph without recursion.
  Add restriction to person count (<1000 persons in the graph).

### CODE REVIEW

**Comment by prculley** [comment]
FYI; We have a few other recursive operations in Gramps, however we usually protect them against loops by maintaining a set or dict that contains a "been there" group of object handles or IDs.  If the recursive routine starts with a check against this set, and sees that it has already processed that object, it just returns.  This protects against loops in the data, and further helps if the data has more than one way to enter a group of objects; you only have to process them once.

This may be better than just waiting for the recursive exception to occur.

**Comment by vantu5z** [comment]
@prculley if I understand you right, we already have checks for processed objects. Issue is occured due to the large number of objects on displayed graph but not loops. We try build graph with more than ~1000 persons and this depth of relations can't be calculated before recursion is runing.

```
def f(i):
    print(i)
    f(i+1)
f(0)
```
This simple example excepts on 995 value with:
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by prculley** [comment]
I'm beginning to get a hint of what is probably happening.  "All connected" does imply that you will eventually touch every person in the tree that has a connection (which for most, will be everybody).  And the way your code is built that could mean a recursion for every person.  You may want to include a test for families in progress; don't recurse if the family for a person is already in progress (after all, it will get attended to when the recursion unwinds).  I think that would significantly reduce the recursion depth, although for large trees you still may get failures.

The other solution is to not use recursion.  The gen.filters.rules.person._deeprelationshippathbetween filter does something like this, however it doesn't use recursion.  It instead processes in a breadth first fashion, rather than depth first.  Maybe you can use this type of processing.

**Comment by vantu5z** [comment]
Should we merge this PR to fix addon for users?
When I have time will rewrite building graph without recursion or use "Glib.idle_add" like in search module.

**Comment by vantu5z** [comment]
rebased

**Pull request merged**
