### PR TITLE
[GraphView]Add Persons node themes & Avatars[v51]

### PR DESCRIPTION
**Pull request by vantu5z**
Resolve [11328](https://gramps-project.org/bugs/view.php?id=11328)

Снимок экрана от 2019-09-26 16-49-14
Снимок экрана от 2019-09-26 16-49-25
Снимок экрана от 2019-09-26 16-49-35

### CODE REVIEW

**Comment by sam-m888** [comment]
Tested and found no issue so far.

Really like this, thanks for improving Graph View 👍 

Can I suggest  a variation:

* With name on top and  picture in middle (on left or right side) with dates in middle and tags accross bottom as is?

example

**Comment by vantu5z** [comment]
Yes, I think about this. No problem to add it.
Have some nuance, what about if image is absent?
Solutions:
* add predefined gender image
* use default theme
* stay as is

**Comment by sam-m888** [comment]
> Have some nuance, what about if image is absent?

You already handle that with these your new themes, have a look at the person node below is just stay as?

2019-09-27 16_29_01-Window

**Comment by romjerome** [comment]
Is it not more 'simple' to use [< div >](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div) tag instead of < table >?

**Comment by vantu5z** [comment]
@romjerome what do you mean about `<div>`? Give little example please.
We use syntax from [graphviz html](http://www.graphviz.org/doc/info/shapes.html#html)

**Comment by vantu5z** [comment]
Снимок экрана от 2019-09-28 16-55-16

**Comment by vantu5z** [comment]
Снимок экрана от 2019-09-28 17-15-58

**Comment by sam-m888** [comment]
That look much better and more compact.  Nice touch making the Name field in the themes **bold** type, makes it stand out.

Testing with example.gramps shows that that the empty marriage/union nodes display code:

gv-themes-default_empyty_marriage-issue

gv-themes-ontheright-empty marraige

**Comment by vantu5z** [comment]
@sam-m888 in your screenshots I see problems with labels. Try to fix this #237

**Comment by gburto01** [comment]
I tested this patch but get this exception when event_str is null.

2019-09-29 11:10:49.995: ERROR: grampsapp.py: line 157: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gramps/gui/grampsgui.py", line 794, in do_activate
    Gramps(self.argparser, self)
  File "/usr/lib/python3/dist-packages/gramps/gui/grampsgui.py", line 647, in __init__
    self._vm.post_init_interface()
  File "/usr/lib/python3/dist-packages/gramps/gui/viewmanager.py", line 549, in post_init_interface
    self.__open_activate(None, None)
  File "/usr/lib/python3/dist-packages/gramps/gui/viewmanager.py", line 965, in __open_activate
    self._post_load_newdb(filename, 'x-directory/normal', title)
  File "/usr/lib/python3/dist-packages/gramps/gui/viewmanager.py", line 1001, in _post_load_newdb
    self._post_load_newdb_gui(filename, filetype, title)
  File "/usr/lib/python3/dist-packages/gramps/gui/viewmanager.py", line 1036, in _post_load_newdb_gui
    self.__change_page(self.notebook.get_current_page())
  File "/usr/lib/python3/dist-packages/gramps/gui/viewmanager.py", line 885, in __change_page
    self.active_page.set_active()
  File "/usr/lib/python3/dist-packages/gramps/gui/views/navigationview.py", line 153, in set_active
    PageView.set_active(self)
  File "/usr/lib/python3/dist-packages/gramps/gui/views/pageview.py", line 335, in set_active
    self.build_tree()
  File "/home/gary/.gramps/gramps51/plugins/GraphView/graphview.py", line 248, in build_tree
    self.graph_widget.populate(self.get_active())
  File "/home/gary/.gramps/gramps51/plugins/GraphView/graphview.py", line 1213, in populate
    self.dot_data, self.svg_data = dot.build_graph(active_person)
  File "/home/gary/.gramps/gramps51/plugins/GraphView/graphview.py", line 2073, in build_graph
    self.add_persons_and_families()
  File "/home/gary/.gramps/gramps51/plugins/GraphView/graphview.py", line 2360, in add_persons_and_families
    self.__add_family_node(fam_handle)
  File "/home/gary/.gramps/gramps51/plugins/GraphView/graphview.py", line 2390, in __add_family_node
    label = self.get_family_label(fam)
  File "/home/gary/.gramps/gramps51/plugins/GraphView/graphview.py", line 2643, in get_family_label
    if event_str[0] and event_str[1]:
IndexError: string index out of range

**Comment by vantu5z** [comment]
@gburto01 thanks for check this! Now it should work.

**Comment by gburto01** [comment]
Yes, it work OK.Thanks

**Comment by vantu5z** [comment]
Снимок экрана от 2019-09-30 14-13-43

**Comment by sam-m888** [comment]
Like the new avatars for person nodes, not sure if people will want it on by default, but I guess we will hear any rumbles and at least they have the option to turn it off. 👍

**Comment by sam-m888** [comment]
unknown right theme
unknown left theme

**Comment by sam-m888** [comment]
Thank you

**Comment by sam-m888** [comment]
Notice issue rebuilt addon is missing avatar images when built,

- [ ] fix missing images in rebuilt addon

**Comment by sam-m888** [comment]
- [x] final check (downloaded via linux & win Gramps addons) includes avatars.

Works 👍

**Comment by johnbickmore** [comment]
@vantu5z Great work on Graph view, really appreciate all the improvements you are making 👍 

Any chance you would consider adding an alternative view that shows only families like **[Kith and Kin](https://kithkinpro.spansoft.org/manual/html/gs_tree_area.php)** does, really gives a great overview and summary of each family when working?

**Pull request merged**
