### PR TITLE
Todo report context

### PR DESCRIPTION
**Pull request by jpschewe**
This pull request adds context to the TODO report as discussed in https://gramps.discourse.group/t/report-for-todo-notes/3674/1

* Context (dates and places) for objects referenced in the report
* Add the ability to filter by note type
* Add the ability to specify the report title

### CODE REVIEW

**Comment by GaryGriffin** [comment]
Should this be branch gramps52 (not gramps51) since 52 is current.

**Comment by jpschewe** [comment]
@GaryGriffin  when I opened the PR gramps51 was current. What changes would you like me to make so that this can be merged?

**Comment by GaryGriffin** [comment]
If you make the same changes to the gramps52 branch, it can be merged. Then you can decide whether to keep the 51 branch changes (to also be merged) or to close it.

**Comment by jpschewe** [comment]
@GaryGriffin OK, so to be clear you'd like a new PR that targets gramps52, correct?

**Comment by GaryGriffin** [comment]
Correct. And you can decide whether to close the gramps51 PR or to have it merged too. Just dont want a change in gramps51 that is stranded and not also done in gramps52.

**Comment by Nick-Hall** [comment]
Yes.  I suggest that changes are made to the current maintenance branch.

Backporting to older versions is optional.

**Comment by jpschewe** [comment]
See https://github.com/gramps-project/addons-source/pull/598 for the gramps52 PR.

**Pull request closed without merging**
