### PR TITLE
Added dependency dialog with link to wiki

### PR DESCRIPTION
**Pull request by zorkmark**
NetworkChart ver_0.0.4 release notes.

Added Dialog box to gpr.py file to alert user to missing python modules.  
Link is also provided in dialog to plugin wiki website for instructions.
Fixed highlight bug related to center_person.
All fixes from 0.0.3.

### CODE REVIEW

**Comment by uxcq** [comment]
> All fixes from 0.0.3.

So ignore [PR65](https://github.com/gramps-project/addons-source/pull/65) ? If so you may want to close it so it does not get applied.

**Comment by sam-m888** [comment]
> So ignore PR65 ? If so you may want to close it so it does not get applied.

@zorkmark  Good question?

**Comment by Paul-Franklin** [comment]
https://gramps-project.org/bugs/view.php?id=9993

**Comment by sam-m888** [comment]
Thank you

**Comment by zorkmark** [comment]
Thanks Sam.

It appears that installing pygraphviz on Windows7, under python 3.x has
some issues.  I assume that this is the case for 8 and 10 as well but
haven't confirmed.  I am investigating alternatives to pygraphviz and
just wanted to give a heads up not to try to package this for Windows
until I can find a better import dependency for cross-platform.
##SELECTION_END## 

Cheers,

Mark



-----Original Message-----

**Pull request merged**
