### PR TITLE
[GraphView] Add search capability[gramps51]

### PR DESCRIPTION
**Pull request by vantu5z**
From #195.
We have requirement of Gtk 3.12 because of Gtk.Popover.
So it should go to Gramps 5.1 ([link](https://github.com/gramps-project/gramps/pull/783#issuecomment-481321833))

### CODE REVIEW

**Comment by fxtmtrsine** [comment]
Has three issues, so not working for me on either on my laptop top (ubuntu 14.04 which is probably expected as end-of-life) or my desktop pc (ubuntu 16.04 - on which it should as it meet the gtk 3.12 or greater requirement)


First issue graphviews toolbar icon is black box with a crossed out circle instead of the usual icon

graphviewnoicon


attempting to use graphview shows a blank canvaas with a toolbar and that straight away pops up an errormessage:

> 23219: ERROR: grampsapp.py: line 157: Unhandled exception
> Traceback (most recent call last):
>   File "/home/fxtmtrsine/gramps/gui/viewmanager.py", line 871, in view_changed
>     self.__change_page(page_num)
>   File "/home/fxtmtrsine/gramps/gui/viewmanager.py", line 885, in __change_page
>     self.active_page.set_active()
>   File "/home/fxtmtrsine/gramps/gui/views/navigationview.py", line 161, in set_active
>     self.goto_active(None)
>   File "/home/fxtmtrsine/gramps/gui/views/navigationview.py", line 196, in goto_active
>     self.goto_handle(active_handle)
>   File "/home/fxtmtrsine/.gramps/gramps51/plugins/GraphView/graphview.py", line 337, in goto_handle
>     self.graph_widget.populate(self.get_active())
>   File "/home/fxtmtrsine/.gramps/gramps51/plugins/GraphView/graphview.py", line 1094, in populate
>     self.search_widget.hide_search_popover()
>   File "/home/fxtmtrsine/.gramps/gramps51/plugins/GraphView/search_widget.py", line 317, in hide_search_popover
>     self.popover_widget.popdown()
> AttributeError: 'Popover' object has no attribute 'popdown'
> 


cancelling that errormessage and attempting to search for people gives:

> 69023: ERROR: grampsapp.py: line 157: Unhandled exception
> Traceback (most recent call last):
>   File "/home/fxtmtrsine/.gramps/gramps51/plugins/GraphView/search_widget.py", line 119, in start_search
>     self.popover_widget.popup()
> AttributeError: 'Popover' object has no attribute 'popup'
> 

this all with ubuntu 16.04 on my desktop

Gramps Settings:
----------------
 python    : 3.5.2
 gramps    : 5.1.0-2c15e38
 gtk++     : 3.18.9
 pygobject : 3.20.0

A quick look at gtk docs shows that popdown and popup where added in gtk 3.22
https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Popover.html#Gtk.Popover.popdown
https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Popover.html#Gtk.Popover.popup

**Comment by fxtmtrsine** [comment]
Thanks 👍 , but when typing I get no results see screenshot

gv search not working

**error messages**


> 2019-06-13 17:16:26.921: WARNING: uimanager.py: line 375: **Duplicate Accelerator <PRIMARY>P
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/fxtmtrsine/.gramps/gramps51/plugins/GraphView/search_widget.py", line 181, in make_search
>     all_person_handles = self.dbstate.db.get_person_handles()
>   File "/home/fxtmtrsine/gramps/plugins/db/dbapi/dbapi.py", line 370, in get_person_handles
>     self.dbapi.execute("SELECT handle FROM person")
>   File "/home/fxtmtrsine/gramps/plugins/db/dbapi/sqlite.py", line 127, in execute
>     self.__cursor.execute(*args, **kwargs)
> sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140177068410624 and this is thread id 140176348260096
> 
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/fxtmtrsine/.gramps/gramps51/plugins/GraphView/search_widget.py", line 181, in make_search
>     all_person_handles = self.dbstate.db.get_person_handles()
>   File "/home/fxtmtrsine/gramps/plugins/db/dbapi/dbapi.py", line 370, in get_person_handles
>     self.dbapi.execute("SELECT handle FROM person")
>   File "/home/fxtmtrsine/gramps/plugins/db/dbapi/sqlite.py", line 127, in execute
>     self.__cursor.execute(*args, **kwargs)
> sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140177068410624 and this is thread id 140176348260096
> 
>

**Comment by vantu5z** [comment]
Hmm, sqlite can't be used in thread.

**Comment by vantu5z** [comment]
now it should work

**Comment by fxtmtrsine** [comment]
> Hmm, sqlite can't be used in thread.
> now it should work

Woohoo

Very timely as the next release has made [sqlite the default](https://github.com/gramps-project/gramps/commit/3a505745f3bb59e5b9b5583b7a0ed2068fd31628) 👍 

Icon is also fixed , thanks.

Love that you have the option to show images also.

optionpics
withpics
noimages

**Comment by fxtmtrsine** [comment]
Minor observation, when you use any of the other charts, and close the family tree from the family tree manager , the viewed chart is blanked (closed and not shown), but with graph view it stays behind after the family tree is closed.

**Comment by sam-m888** [comment]
Works well for me in quick testing, people will really like this one, great enhancement 👍

**Comment by vantu5z** [comment]
@sam-m888, thanks, I like it too:)
We have some little problem like double result (see on screenshot - I0628).
I think this is the thread handling issue.
It can be reproduced by fast `Enter` click. And some times when type in search entry.

**Comment by sam-m888** [comment]
> We have some little problem like double result (see on screenshot - I0628).

Ok, I see and can reproduce the issue, can the results from the search be a [python set](https://docs.python.org/3.7/library/stdtypes.html#set-types-set-frozenset) to stop duplication?

**Comment by vantu5z** [comment]
@sam-m888 @fxtmtrsine , can you test fix for duplication issue?

**Comment by sam-m888** [comment]
> set() can't help us because problem was at GLib.idle_add().

Thanks for the explanation.

Duplication seems to be resolved for the few test I did.

fyi because of previous update the file is conflicting.

**Comment by vantu5z** [comment]
PR rebased

**Pull request merged**
