### PR TITLE
DescendantsLines addon: added header and footer

### PR DESCRIPTION
**Pull request by giansalvo**
Probably to be merged after PR 273
https://github.com/gramps-project/addons-source/pull/273

### CODE REVIEW

**Comment by prculley** [comment]
Could you rebase this to maintenance/gramps51?  At the moment we are doing all the addon work there and periodically merge up to master.  This is because addons-source master is not used at the moment; and won't be until we update Gramps master to gramps52 status.

**Comment by giansalvo** [comment]
> Could you rebase this to maintenance/gramps51?
Sure! But I'm not very good with git commands, can you help me? Otherwise I'll just open a new PR in a new branch... Let me know...

**Comment by prculley** [comment]
Assuming you have cloned the entire addons-source to your local git.
`git checkout maintenance/gramps51`
`git pull`  to make sure it is up to date
`git checkout DescendantsLines_header_footer`
`git rebase upstream/gramps51`
`git push -f origin DescendantsLines_header_footer`

For future work, just start your branch off of upstream/gramps51

**Comment by giansalvo** [comment]
Thanks, but it didn't work. I opened manually https://github.com/gramps-project/addons-source/pull/280 and closing this one

**Pull request closed without merging**
