### PR TITLE
Add a new addon for exporting gedcom specific to the geneanet website.

### PR DESCRIPTION
**Pull request by grocanar**
Hi

I have developped a plugin to integrate some "non standard" gedcom extension specific for the geneanet website.
It s based on the GedcomExtension plugin that i have extended.

-Some role for personnal event become witnesses
- the ability not to use depot information for the sources.

### CODE REVIEW

**Comment by dsblank** [comment]
Great!

**Comment by daleathan** [comment]
This really would be better as part of the existing [GEDCOM extension](https://gramps-project.org/wiki/index.php?title=GEDCOM_Extensions). As that's why the GEDCOM extensions checkboxes allow you to select which part to enable. If the options are mutually exclusive then the GEDCOM extension should handle that or have the ability to recognize  the [destination](http://www.tamurajones.net/GEDCOMSOURandDEST.xhtml)  program and only enable those custom extensions.  It would also be nice for the existing GEDCOM extension to have a separate page or a clearly titled section that mentions that it is not part of the filters above.

**Comment by sam-m888** [comment]
Thank you for this extension :+1: 

In testing it, loaded once I changed the  ` gramps_target_version = '4.2',` to '5.0' it worked for me on master, did you intend for this to only be applied only to the maintenance/gramps42  branch? If not please update the gramps target version.

gedcomforgeneanet-selection
gedcomforgeneanet-export-options

@grocanar Question: What does the word "depot" refer to?

I opened the created GEDCOM in a texted editor and it looks like it was create Ok, untested with the destination program/website, which I assume you've done?

Also installed the existing GEDCOM Extension and found no issue with both being installed at the same time. (Apart from duplication.)

**Comment by sam-m888** [comment]
@daleathan Can you please submit a feature request for the GEDCOM extension. Thanks

**Comment by grocanar** [comment]
Hi Sam

i only test it in 4.2

||i was wondering on what |gramps_target_version means|

|if there s 5.0 value does people see it wen using 4.2?|

|depot means repository in french. I forget to traduce it.|

|
|

|and two people have succesfully test it on geneanet.
|

|I will change depot to repository and update the traduction at lest in 
french.|

|
|

**Comment by romjerome** [comment]
@grocanar 

Maybe some extra files?

* GedcomforGeneanet/locale/GedcomforGeneanet/LC_MESSAGES/addon.mo
* GedcomforGeneanet/locale/fr/LC_MESSAGES/addon.mo
* GedcomforGeneanet/po/POTFILES.in
* GedcomforGeneanet/po/fr.po

You do not need them on source. It seems to be a mixup during your tests and devel?

**Comment by grocanar** [comment]
Le 02/05/2016 09:42, romjerome a écrit :
>
> @grocanar <https://github.com/grocanar>
>
> Maybe some extra files?
>
>   * GedcomforGeneanet/locale/GedcomforGeneanet/LC_MESSAGES/addon.mo
>   * GedcomforGeneanet/locale/fr/LC_MESSAGES/addon.mo
>   * GedcomforGeneanet/po/POTFILES.in
>   * GedcomforGeneanet/po/fr.po
>
> You do not need them on source. It seems to be a mixup during your 
> tests and devel?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gramps-project/addons-source/pull/28#issuecomment-216124571>
>
hmm i should agree :)
i m still new at using git and the organisation of source and devel.

what should i do to clea the mess?
should i remove the two github pull-request to make better one?

**Comment by grocanar** [comment]
I remove this pull request.
i will make a cleaner one based on comments soon

**Pull request closed without merging**
