### PR TITLE
[GraphView] code revision and fixes (Gramps50)

### PR DESCRIPTION
**Pull request by vantu5z**
Change to discuss (refactoring DotGenerator to DotSvgGenerator):
- move generation of SVG data to `DotGenerator.make_svg` from `GraphWidget.populate`;
- handle closing `StringIO()` in `DotGenerator`:
  - add `__del__` method to free dot file stream on destroy;
  - add `init_dot` method to `DotGenerator` with:
    - `StringIO().close()` to free dot file stream;
    - writing start data of dot file;
- rename `DotGenerator` to `DotSvgGenerator`;
- `DotSvgGenerator.build_graph` returns dot and svg data, and after `DotSvgGenerator` can be destroyed;

I don't know is this right way and maybe we should not do so refactoring.
Maybe is enough to call `StringIO().close()` on `DotGenerator` deleting (if needed).

Changes:
- sort imports;
- move load bookmarks to `populate` method;
- rename variables;
- add/edit comments;
- shaking item after scroll (code refactor, think this more clear);
- graph clear on rebuilding (remove root item)
remove root item (with children) before rebuilding graph removes all used items in `Animation` class.

Cleanup:
- remove unused cairo from import;
- remove unused active person item from `GraphvizSvgParser`;
- remove useless `get_dot` method from `DotGenerator`;

Fixes:
- show tooltip on home person hover (as any other nodes);
- maybe reduce memory leak;
- animation toggle in config dialog (issue 10712);
- generation count (issue 10717);
- show ancestors for father and mother.

### CODE REVIEW

**Comment by sam-m888** [comment]
@vantu5z Can you provide a short description on what this pr fixes or changes please?

**Comment by vantu5z** [comment]
I think handle of closing StringIO() is better. So I did it as before (creating DotGenerator on every populate) but add removing.

**Comment by sam-m888** [comment]
@SNoiraud Do you have time to review this? 

My test show no issues so far, but I'm not too sure on the code side of what's been updated eg: StringIO() etc.

**Comment by SNoiraud** [comment]
I now use this since one week. I found no problems for the moment.

**Comment by vantu5z** [comment]
Screenshot of diable/enable animate options in config:

**Comment by vantu5z** [comment]
@SNoiraud, can you look if all is fine?

**Comment by SNoiraud** [comment]
fix 10712: OK for me.
add comments: OK
fix generation count : OK for me.
fix ancestors generation display: OK for me.
try to fix crash on get theme colors (issue 10716): cannot reproduce this, so not tested.
I think you can merge it.

I use it since 21 may for all other patches.

**Comment by vantu5z** [comment]
Could someone to rebuild addon?

**Comment by wroldwiedbwe** [comment]
> Could someone to rebuild addon?
> Try to rebuild it gramps-project/addons#8

@sam-m888 Can you do this please 🥇 ?

**Comment by prculley** [comment]
I just accepted https://github.com/gramps-project/addons/pull/8 so it can now be downloaded by users.

A quick test doesn't look so good...
graph_view

**Comment by jralls** [comment]
I remember a bug about text not fitting the boxes, but I can't find it.

**Comment by prculley** [comment]
My machine is using Graphviz 2.41 on Windows 10

I just tested The "Edit/Preferences/General/Use Alternate Font Handler for GUI and reports..." which only appears on Windows machines.  The PANGOCAIRO_BACKEND font handler (set by this option) comes in several varieties, the default one for Windows machines (win32) doesn't seem to be able to choose fonts with all the utf-8 characters present sometimes.  The Alternate font handler (fc), is basically the same one as used on Linux.  While it does a better job of picking fonts with all the utf-8 characters, sometimes the chosen fonts are not as close to the desired appearance.  So the user has to decide which he likes better...

As it happens, I was using the default Windows font handler (win32) when I took the picture above.  I just tried using the Alternate handler and GraphView worked correctly.  Looks like something about the win32 handler is telling your code the size is wrong...  
graph_view

**Pull request merged**
