### PR TITLE
Fix DynamicWeb for exception on config setting

### PR DESCRIPTION
**Pull request by prculley**
Fixes [#10483](https://gramps-project.org/bugs/view.php?id=10483)

Bug was side effect of the changes for dark theme support...
2nd bug was side effect of changes for place editor...

### CODE REVIEW

**Comment by sam-m888** [comment]
Tested and does not work see bug report.

**Comment by adamvazquez82** [comment]
**preferences.place-lang** was removed in https://github.com/gramps-project/gramps/pull/368

**Comment by prculley** [comment]
@sam-m888 @adamvazquez82 Thanks for testing.
Seems I should wipe out my gramps.ini once in a while; I was not seeing the bug because I still had the old 'preferences.place-lang' in my gramps.ini.

**Comment by sam-m888** [comment]
@prculley @adamvazquez82  Thank you

**Pull request merged**
