### PR TITLE
Add new addon [EventDescriptionEditor] [gramps51]

### PR DESCRIPTION
**Pull request by Mattkmmr**
The Event Description Editor tool allows users to select several events, search their event descriptions for a substring and change the description or the substring to a new one. This feature was requested in [#4757](https://gramps-project.org/bugs/view.php?id=4757) and in [#2656](https://gramps-project.org/bugs/view.php?id=2656).

### CODE REVIEW

**Comment by prculley** [comment]
Looked this over and it appears to work.

But I think you need to add the "parent" parameter for the OkDialog; on my multi-monitor system it did not appear over Gramps, but centered on a different monitor.

Some stylistic comments;
You may also want to look into the Python string replace function, it would considerably simplify some of your code and make it a bit more readable.  If you used that, you could replace the 'count' function with "if sub_str in description:" type tests.

Also, I think pylint would complain about the use of single character variables.

**Comment by Mattkmmr** [comment]
[Wiki documentation](https://gramps-project.org/wiki/index.php/Addon:EventDescriptionEditor)

**Comment by prculley** [comment]
I see this still has a Work in progress flag???  Planning more fixes?

**Comment by Mattkmmr** [comment]
I updated some code, but I do not plan more features/fixes.

**Comment by prculley** [comment]
Then you should turn off 'work in progress' so we know it may be eligible for merging.

**Comment by Mattkmmr** [comment]
@prculley I don't think that I can add or remove labels. @sam-m888 added them originally.

**Comment by prculley** [comment]
I didn't realize that labels were limited to the privileged few; @sam-m888 can we change this?

**Comment by Nick-Hall** [comment]
I have sent an invitation.

**Pull request merged**
