### PR TITLE
Graph view animation [gramps51]

### PR DESCRIPTION
**Pull request by vantu5z**
- class for animation added;
- apply animation for moving to active person (on button click);
- add ability to develop "move to person" feature;
- add combobox with bookmarked persons to navigate to them (if in current tree);
- add shake animation after moving to person.

We need someone who know about threads to look how it realized.
Testing is needed.

### CODE REVIEW

**Comment by vantu5z** [comment]
@SNoiraud , look this PR. Now you can use "move_to_person" function to move (with animation) to specified person by handle. We just need some friendly person chooser to realize "go to person" feature.

**Comment by SNoiraud** [comment]
Seems good to me.
I have tested with bookmarks and If the bookmark is in the tree, we can animate to this person.
The patch is the following : 
[goto_other.patch.txt](https://github.com/gramps-project/addons-source/files/1297071/goto_other.patch.txt)

**Comment by vantu5z** [comment]
@SNoiraud , patch applied with little changes.
And shaking animation after moving to person was added. It helps to see this person, because we don't highlight it anyhow and it can be not in center of screen.

**Comment by SNoiraud** [comment]
When we add a new bookmark, we need to change the combobox. So, we need to add the following in the change_db method : 
        self.dbstate.connect('active-changed', self.graph_widget.load_bookmarks)

**Comment by SNoiraud** [comment]
Last patches doesn't work : 
TypeError: move_to() missing 1 required positional argument: 'animated'
Warning: DbBsddb: Exception occurred in callback function.
Traceback (most recent call last):
  File "/home/gramps/gramps50/gramps/gen/utils/callback.py", line 405, in emit
    fn(*args)
  File "/home/serge/.gramps/gramps50/plugins/GraphView/graphview.py", line 258, in goto_handle
    self.graph_widget.populate(self.get_active())
  File "/home/serge/.gramps/gramps50/plugins/GraphView/graphview.py", line 698, in populate
    self.goto_active(None)
  File "/home/serge/.gramps/gramps50/plugins/GraphView/graphview.py", line 641, in goto_active
    self.animation.move_to_person(self.active_person_handle, animation)
  File "/home/serge/.gramps/gramps50/plugins/GraphView/graphview.py", line 2145, in move_to_person
    self.move_to((x, y), animated)
TypeError: move_to() missing 1 required positional argument: 'animated'

**Comment by vantu5z** [comment]
@SNoiraud , fix missing argument. And make separated counters for shaking - it needed to prevent incorrect shaking of items on quickly target switching.

**Comment by SNoiraud** [comment]
In some case, move_to doesn't go to the good person.
it happens with "go to the active person" or "go to to the bookmark person".
Is it related to shake? I don't know.

**Comment by vantu5z** [comment]
I don't have test alot. But known issue: if zoon when it scroll to person - you go to incorrect coordinates, because track calculated before zooming. I think about dynamic calculation.

**Comment by SNoiraud** [comment]
I don't scroll.

**Comment by SNoiraud** [comment]
I didn't reproduce the move_to problem until now.  I suppose the last patch solves the problem.

**Comment by vantu5z** [comment]
Now trace to person calculated dynamically. We can move, scroll or .. when animation in motion.
Maybe we need stop animation when we try to move tree by mouse?

Testing is needed.

**Comment by SNoiraud** [comment]
It's OK for me.
try to zoom when moving on long distances : OK
try to move during scrolling the window : OK
I try to add a video to show this (if it's not too big 6.2MB)
[PR89.mp4.txt](https://github.com/gramps-project/addons-source/files/1306740/PR89.mp4.txt)
You can remove the .txt to view it.

**Comment by vantu5z** [comment]
Good! :)
But i found if we add new bookmark - combobox not updated as expected. And you?

And some ideas:
Maybe don't add bookmarks that not in current tree?
If we select one from combobox - we can't select it again while it selected.
It would be nice to have filterable combobox which filter list when enter name. And not for bookmarks but for persons in the current tree.

**Comment by SNoiraud** [comment]
I have the same problem. When I tested it it worked.
We need to add self.graph_widget.load_bookmarks()
in to goto_handle method.

**Comment by SNoiraud** [comment]
> Maybe don't add bookmarks that not in current tree?

The best way to do this should be to have a method : Is_this_person_present_in_the_tree
If False, we don't add it to the combobox.
Is the get_item_by_title method the solution ?

> If we select one from combobox - we can't select it again while it selected.

I look at this.

**Comment by SNoiraud** [comment]
I have one solution : 
[bkmarks.patch.txt](https://github.com/gramps-project/addons-source/files/1308310/bkmarks.patch.txt)

**Comment by vantu5z** [comment]
I test it after weekend :)

**Comment by sam-m888** [comment]
Very nice animation 👍  Will test more next week.

**Comment by SNoiraud** [comment]
After last patch (bkmarks.patch.txt), we need to remove line 596 in __init__ : 
self.load_bookmarks()

  File "/home/serge/.gramps/gramps50/plugins/GraphView/graphview.py", line 596, in __init__
    self.load_bookmarks()
  File "/home/serge/.gramps/gramps50/plugins/GraphView/graphview.py", line 617, in load_bookmarks
    present = self.animation.get_item_by_title(bkmark)

**Comment by vantu5z** [comment]
Combobox updating works for me :)

**Comment by SNoiraud** [comment]
OK for me. very nice.

**Comment by SNoiraud** [comment]
I use it since september. I had no problem.
The shaking is very fast and short. I have a patch to modify the speed and count.
If you apply it, I think we could merge it.
[count.patch.txt](https://github.com/gramps-project/addons-source/files/1629257/count.patch.txt)

**Comment by vantu5z** [comment]
Add your patch.
For me animation speed is very fast, so I set `GLib.usleep(20 * self.speed)` between steps.
Fix shaking animation when switch to other person and shaking in progress.

**Comment by sam-m888** [comment]
Thank you 👍 

Addon rebuilt in https://github.com/gramps-project/addons/commit/0fdfe642e5397157b3ca109c6d97d5583efe9c47

**Pull request merged**
