### PR TITLE
Croatian translation for addons[gramps51]

### PR DESCRIPTION
**Pull request by milotype**
Some updates, but mostly new croatian translations for all addons.

### CODE REVIEW

**Comment by sam-m888** [comment]
@milotype Are you sure you want this on the Gramps master branch and not the current release gramps50?

**Comment by milotype** [comment]
Well, ideally I guess on both, but whatever you find more usefull. As I do my commits one-by-one over GitHub directly, it's a lot of work for both branches. Can you guys duplicate it for gramps50 (if at all necessary)?
Should I in general rather update the highest "maintenance" branch?

**Comment by sam-m888** [comment]
> Should I in general rather update the highest "maintenance" branch?

Yes the **maintenance/gramps50**  branch is periodically merged to master (sorry not the other way around :( )

**Comment by milotype** [comment]
Can you push/pull (or whatever needed) this "commit-package" to the **maintenance/gramps50 branch** instead of to master?

**Comment by prculley** [comment]
I have manually shifted these commits to gramps50, rebuilt etc.  And then merged up into gramps51 and rebuilt there as well.  So your translations should appear in all the addons for each (5.0.x, 5.1.x) version of Gramps.

**Comment by milotype** [comment]
@prculley Thank you! ... I found one small error in addon "NoteCleanup" (true for both 5.0.x and 5.1.x branches). The file `hr-local.po` is not placed in the po-subfolder.
Current location:
`addons-source/NoteCleanup/hr-local.po`
Should be:
`addons-source/NoteCleanup/po/hr-local.po`

I've checked all other addon folders and they are fine.

**Pull request closed without merging**
