### PR TITLE
Life line chart view update5

### PR DESCRIPTION
**Pull request by CWSchulze**
- fixed missing button icon file in the manifest
- download dependencies dialog changed due to user error reports
  - The user can no longer hide the warning. Either install dependencies or uninstall plugin. Hiding the missing module warning causes import errors which cannot be hidden, so it doesn't make sense to do that...
- Fixed missing class member variable (Bugtracker ID 0012223) sha 4be0664

### CODE REVIEW

**Comment by CWSchulze** [comment]
Any suggestion why this pipe is failing?

**Comment by PQYPLZXHGF** [comment]
Following the link  https://travis-ci.org/github/gramps-project/addons-source/builds/760847870#L2540  shows 

> LifeLineChartView/lifelinechartview.gpr.py:147:        # requirements or uninstall the plugin. If this warning would be 
> ERROR - Trailing whitespace found in source file(s)

So line 147 has a trailing whitespace, is that what you mean by "pipe failing"?

**Comment by CWSchulze** [comment]
Thanks... I looked at the log file but didn't see the error message. Maybe sunday nights are not the best time for bugfixes...

**Comment by PQYPLZXHGF** [comment]
@CWSchulze  All good 👍 

@Nick-Hall @sam-m888 @jralls @dsblank Looks like travis-ci.org is shutting down for open source projects what will Gramps project replace this with may [GitHub Actions](https://github.com/features/actions)?

> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information. 

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

https://blog.travis-ci.com/oss-announcement

https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

**Pull request merged**
