### PR TITLE
GenealogyTree: Add new report for sandclock of family[gramps50]

### PR DESCRIPTION
**Pull request by hahnjo**
This is modelled after DescendTree which also uses a single class to
reuse as much code as possible. Tested with real data on Gramps 5.0
and basic tests on Gramps 5.1 / master.

### CODE REVIEW

**Comment by sam-m888** [comment]
Thanks for the new report.

Do I have to use any special settings to have the report display correctly when output to pdf as if prints one blank page and you can partiality see the report at the bottom of page 2 (see screenshots below) ?

sandclock-of-family-report-example-output-defaults-50
sandclock-of-family-report-options-default-50
menu-sandclock-of-family-50

**Comment by hahnjo** [comment]
> Do I have to use any special settings to have the report display correctly when output to pdf as if prints one blank page and you can partiality see the report at the bottom of page 2 (see screenshots below) ? Edit: don't worry this looks to be related to https://gramps-project.org/bugs/view.php?id=10512 )

Right, the page is probably just too small and LaTeX does its layout-thing. You could try larger dimensions like `a3paper`...

**Comment by SNoiraud** [comment]
I have the same problem : I only see my tree partially. The page size is inoperative for all page format.
I tried to solves this adding the template directive after the genealogytree:
\genealogytree[
template=database pole reduced,
...

I can now see all my tree. The problem is we can't resize more than 400% 

To test it, i have the following patch:
diff --git a/gramps/gen/plug/docgen/treedoc.py b/gramps/gen/plug/docgen/treedoc.py
index 4918090ae..074edc52f 100644
--- a/gramps/gen/plug/docgen/treedoc.py
+++ b/gramps/gen/plug/docgen/treedoc.py
@@ -359,6 +359,7 @@ class TreeDocBase(BaseDoc, TreeDoc):
 
     def start_tree(self, option_list):
         self.write(0, '\\genealogytree[\n')
+        self.write(0, 'template=database pole reduced,\n')
         self.write(0, 'processing=database,\n')
         if self.marriage:
             info = self.detail + ' ' + self.marriage

**Comment by Nick-Hall** [comment]
> \genealogytree[
> template=database pole reduced,
> ...


Alternatively, if the option is only required for this report, it can be added to the [options](https://github.com/gramps-project/addons-source/blob/fca95f5798492fa06f236d2a74f3394270a07482/GenealogyTree/gt_sandclock.py#L98) list.

**Comment by hahnjo** [comment]
I'm not really see how these problems are related to this PR: The new report might generate larger trees (because it considers roughly twice as many nodes going upwards), but I guess you could also get cropped graphs with the existing sandclock or even other genealogytree reports...

**Comment by Nick-Hall** [comment]
@hahnjo Yes, I agree.  A separate PR should be created for the page size issues.

**Comment by sam-m888** [comment]
Thank you

**Comment by hahnjo** [comment]
> @hahnjo Yes, I agree. A separate PR should be created for the page size issues.

Another route (that I'm taking) is to only use the graph database from the sandclock report and have your own LaTeX file around that, customized to your needs. I'll probably try to add a new option to only export the .graph file, so that users don't need to manually copy the database :-)

**Comment by sam-m888** [comment]
Addon has been rebuilt with your new report.  Please update your addons.[1]

Thank you

[1]
https://gramps-project.org/wiki/index.php/5.0_Addons#Installing_Addons_in_Gramps

>

**Comment by hahnjo** [comment]
> Addon has been rebuilt with your new report.

Thanks! I have some more fixes and enhancements that I'll submit after the holidays.

**Pull request merged**
