### PR TITLE
[GraphView] [5380] fix font size and image position

### PR DESCRIPTION
**Pull request by vantu5z**
- add 'px' how it suggested at bugtracker [5380];
- set default font size - 14;
- change coef for image correction to '0' (linux);
- remove not needed coefficients;

it works for me on linux with:
graphviz 2.38.0-13
pygoocanvas 0.14.1-7

### CODE REVIEW

**Comment by SNoiraud** [comment]
I think we need to add '+ "px"' at line 998 too.

**Comment by SNoiraud** [comment]
I don't know how to solve the version problem in graphview.gpr.py.
It shoul be 1.0.68 now.

**Comment by vantu5z** [comment]
I don't know how to solve the version problem too.
I can create new PR or you can add changes by yourself.

**Comment by vantu5z** [comment]
Found that coefficient = 1.6 not needed anymore.
1039        width = float(attrs.get('width').rstrip(string.ascii_letters))*1.6
1040       height = float(attrs.get('height').rstrip(string.ascii_letters))*1.6

**Pull request merged**
