### PR TITLE
Update DescendantBooks.gpr.py

### PR DESCRIPTION
**Pull request by emyoulation**
Register as Books capable Reports list.

### CODE REVIEW

**Comment by GaryGriffin** [comment]
Should this be in master or maintenance51?

**Comment by emyoulation** [comment]
Probably in both 5.1 and 5.2 maintenance branches.

Nick has suggested that the addons-source "master" branch serves no function and might be eliminated.

**Comment by GaryGriffin** [comment]
please change to appropriate branch (gramps51 or gramps52).

**Comment by Nick-Hall** [comment]
Rebased onto _gramps52_.

**Pull request merged**
