### PR TITLE
Fix file output location for DenominoViso

### PR DESCRIPTION
**Pull request by jstockman67**
Prevent error where default location is in users program files directory on Microsoft windows and other os's

"Failure writing /DenominoViso.xhtml: [Errno 13] Permission denied:
see http://gramps.1791082.n4.nabble.com/DenominoViso-report-error-td4685342.html

### CODE REVIEW

**Comment by jstockman67** [comment]
Looks the same as this issue https://gramps-project.org/bugs/view.php?id=7095

**Comment by jstockman67** [comment]
Do I need to do anything else on this?

Can someone provide an idea of how long it takes to be accepted?

**Comment by prculley** [comment]
We are supposed to let PRs set for at least a week before accepting them; this allows time for people to comment on them.
That said, I will get it accepted and uploaded now.

**Comment by jstockman67** [comment]
Thank you :)


9 Jun 2019, 7:22 am by notifications@github.com:

**Pull request merged**
