### PR TITLE
[GraphView] right click menu updates [Gramps50] recreation

### PR DESCRIPTION
**Pull request by vantu5z**
Recreation of #199.

PR was reverted since [issue 11161](https://gramps-project.org/bugs/view.php?id=11161#bugnotes).

Now it should work. [fix](https://github.com/gramps-project/addons-source/commit/dfab772359626fdf70ea3910cbef9774e34bdbba)
I have forgot about this [link](https://github.com/gramps-project/addons-source/pull/120#issuecomment-370108363).

Anyway we should test it before merge.

### CODE REVIEW

**Comment by vantu5z** [comment]
@adamvazquez82 @PQYPLZXHGF @johnbickmore @wroldwiedbwe
Can you make tests. If it works now.

**Comment by Mattkmmr** [comment]
@vantu5z Right click menus show up now. Switching between persons (right click menu) does not work. The animation is shown, but the view isn't updated.

**Comment by vantu5z** [comment]
This is right behavior. If you choose some one from menu, view just navigate you to this person but not make it active. If the choose person not in the graph than graph will be rebuild.

**Comment by wroldwiedbwe** [comment]
> Can you make tests. If it works now.

@vantu5z Yes 👍 works with my old laptop that has ubuntu 14.04 and gtk 3.10.8, thanks :)

test
test2
test3
test4

**Comment by adamvazquez82** [comment]
@vantu5z Works for me too 👍

**Comment by sam-m888** [comment]
@vantu5z It works on each of the VM's I've tested with (including one that Ubuntu 14.04 )

**Comment by vantu5z** [comment]
I think it ready to be merged and rebuild.
@sam-m888 can you do this?

**Comment by sam-m888** [comment]
Thank you.

**Pull request merged**
