### PR TITLE
Reverse commit 5c3da03d2a06c

### PR DESCRIPTION
**Pull request by uxcq**
Removed by https://github.com/gramps-project/gramps/commit/2993d59c2ef45f9f7384b1f03b88d3a183b5ec4c

### CODE REVIEW

**Comment by sam-m888** [comment]
Tested existing JSON import addon and see the error this PR fixes:

`2016-11-26 09:07:09.739: WARNING: _manager.py: line 279: Plugin error (from 'JSONImport'): No module named 'gramps.gen.lib.struct'`

Thank you

**Comment by sam-m888** [comment]
Needs a bit more!

**Comment by Nick-Hall** [comment]
I removed the Struct class.  It wasn't used anywhere in the core code.

**Comment by uxcq** [comment]
Sorry, I believe I had reverted that class back..  :(

Well thats sad, third party addons are second class and don't count? Will you (both) be fixing this addon to at least work like it does in Gramps 4.2 that uses that exact class!

**Comment by Nick-Hall** [comment]
The file I removed doesn't exist in gramps42.

**Comment by Nick-Hall** [comment]
Fixed and improved json import/export in commit 44ca8bbeb133c58f56f30f43b8a3bb7c39c03728.

**Comment by sam-m888** [comment]
> Well thats sad, third party addons are second class and don't count? ....Will you (both) be fixing this addon

@uxcq Thanks for testing and reporting the issue, without you it may have been overlooked. Keep in mind that third party addons are ideally meant to be looked after by there authors, but in alot of cases it scratches that persons itch and they have shared the addon here as is. Please remember we are all volunteers here, and from my perspective as I don't talk for the project think of Gramps as a Gift (that anyone can improve) and not a Product that you buy (as is with no chance for improvement).  

@Nick-Hall Thanks for updating/fixing the JSON addon, I've rebuild it in https://github.com/gramps-project/addons/commit/e45ce9e0d2f213278861517bf452584ff9d3171c

**Comment by uxcq** [comment]
Sorry guys, feeling a bit sheepish, didn't mean to come off as demanding anything, I chalk it up to lack of sleep. I retire next year and intend to help. Yes I agree Gramps is a gift, but one that really needs a clean up and good lick of paint :)

Thanks for fixing the JSON addon 👍

**Comment by Nick-Hall** [comment]
@uxcq I agree with you that the Gramps code needs a clean up.  I am tidying up the new dbapi code at the moment.  Unfortunately, sometimes I could break something in the process.

The core code is a priority, but please let us know about isssues with addons.

We always welcome new developers.  Let us know if you need any help getting started.

**Pull request merged**
