### PR TITLE
Hebrew translation for GetGov & Phototagging Gramplets

### PR DESCRIPTION
**Pull request by avma**

### CODE REVIEW

**Comment by sam-m888** [comment]
Do you really want this in Gramps master and not the current gramps51 branch?

**Comment by avma** [comment]
Isn't master the source for the rest, (gramps50, gramps51..)?

**Comment by prculley** [comment]
For the Gramps main code, during early development, new code is put into master.  So if the translator is keeping up to date, all changes can happen there.  If the translator doesn't get his translations in before release, it is best to make the changes into the most current released maintenance branch.

For addons it is a bit different.  If the addon was released directly into a maintenance branch (very common) then translation changes should be made there.

For both Gramps main code and addons, we periodically merge all changes from the most recent maintenance branch into master, and sometimes from a lower branch into an upper one.

So if you are updating an addon and you think that you want your updates to appear for a particular version of Gramps, make the changes to that associated branch.  Either merge your changes to higher branches yourself (extra PRs), or make a note that you hope that we will do this for you, particularly if you make your changes to an older maintenance branch than the most recent.

**Comment by avma** [comment]
Thank you prculley for clarifying this for me.
So I guess this should go into maintenance/gramps51...
Should I create new pr's and close this one, or can you move them across?

**Comment by prculley** [comment]
I rebased onto gramps51, then rebuilt the addons and committed/pushed everything so the new translations should be available.

**Comment by avma** [comment]
Thanks Paul....

**Pull request closed without merging**
