### PR TITLE
[GraphVeiw] right click menu updates [gramps50]

### PR DESCRIPTION
**Pull request by vantu5z**
Move right-click menu to separate class, add actions class.
Add items to menus: remove, tags, bookmarks.

Resolve:
- issue [10870](https://gramps-project.org/bugs/view.php?id=10870)
- @SNoiraud  idea [link](https://github.com/gramps-project/addons-source/pull/195#issuecomment-479144849)

#### Background menu:
- show images
- highlight the home person
- show full dates
- show places
- show tags
- show animation
- line types >
  - direct
  - curves
  - ortho
- about graph view

#### Person menu:
- edit
- copy
- remove
- tags >
  - select tags for person
  - organize tags
- spouses >
  - add spouse (new family)
  - ... list of spouses ...
- siblings >
  - ... list of siblings ...
- children >
  - ... list of children ...
- parents >
  - ... list of parents ... / add parents
- related >
  - ... list of related ...
- set as home person
- add to bookmarks / remove from bookmarks
- about graph view

#### Family menu:
- edit
- remove
- tags >
  - select tags for family
  - organize tags
- spouses >
  - father person / add father
  - mother person / add mother
- children >
  - add child to family
  - ... list of children ...
- about graph view

### CODE REVIEW

**Comment by vantu5z** [comment]
Should I add something else?

**Comment by SNoiraud** [comment]
> Should I add something else?

for me, I don't see anything to add in 5.0.

In the menu,
If we right click on a man, We have Spouses -> add spouse: OK
If we right click on a woman, We have Spouses -> add spouse: NOK perhaps we should show Spouses or Bride for a man and Husband or groom for a woman

**Comment by vantu5z** [comment]
> If we right click on a woman, We have Spouses -> add spouse: NOK perhaps we should show Spouses or Bride for a man and Husband or groom for a woman or Partner.

Hm.. I believe that `spouse` is universal word for man or woman like `partner` but more official.
Anyway this menu adds new family with selected person, maybe set it as 'add new family'?

**Comment by SNoiraud** [comment]
> I believe that `spouse` is universal word for man or woman

Yes, You are right.

> Anyway this menu adds new family with selected person, maybe set it as 'add new family'?

Yes, I agree

**Comment by SNoiraud** [comment]
We have a problem with the busy cursor when we click on a person and this person has no ascendant.

**Comment by SNoiraud** [comment]
OK for me.

**Comment by johnbickmore** [comment]
@vantu5z I don't see it offered in addons when I check in Gramps, does something else need to be done?

**Comment by vantu5z** [comment]
Yes, it should be rebuild. But I don't have access to do this.

**Comment by adamvazquez82** [comment]
@sam-m888 With the new update the context menus do not work, tested with Windows AIO 5.01 (right click gives nothing) and Ubuntu 14.04 (I see the briefest flash of shadow from the context menu), are the changes compatibility with gtk3.10?  You may want to roll this back before people complain or fix it. Shouldn't you test using the oldest minimal requirements?

@vantu5z @SNoiraud You may also want to setup a virtual machine that has the oldest minimal requirements that Gramps uses!

**Comment by vantu5z** [comment]
@adamvazquez82 This is strange, because I don't change popup call.
I have similar behavior with PhotoTaggingGramplet #175 ([10866](https://gramps-project.org/bugs/view.php?id=10866))
Can you test this popup call:
```
def show_menu(self, event=None):
    """
    Show popup menu.
    """
    if (Gtk.MAJOR_VERSION >= 3) and (Gtk.MINOR_VERSION >= 22):
        self.popup_at_pointer(event)
    else:
        self.popup(None, None, None, None, 0, 0)
```
and this:
`self.popup(None, None, None, None, 0, Gtk.get_current_event_time())`

**Comment by vantu5z** [comment]
Try to fix this commit: aaadacd54ca9e178428a47cd2f6c5fc64480d5ea

**Comment by adamvazquez82** [comment]
@sam-m888 Can this be reverted (like requested by @vantu5z on the bug tracker) please?

**Comment by vantu5z** [comment]
@sam-m888 @adamvazquez82 Changes was reverted.
Addon need to be rebuild.

**Comment by sam-m888** [comment]
@vantu5z <https://github.com/vantu5z> done, thank you.

**Pull request merged**
