### PR TITLE
"TimeLines Map" - Addressed some issues on GitHub and Discourse

### PR DESCRIPTION
**Pull request by tbmapman**
- Added a default configuration option to decide what to do after the plugin has loaded and you change the active person.
- Added a "Set View" button on the bottom control panel.
- Added "audience" and "help_url" and changed "status" in the register file 
- Changed default initial view to "Active Person" to match other geography views (behaviour can be changed in configuration options).
- Changed instances of "Individual" to "Person" to match glossary.
- Changed instances of "GeoTimeLines" to "TimeLines Map" to standardize the name.
- Changed default config setting "Display markers for unknown ancestors" to "Do Not Show" (behaviour can be changed in configuration options).
- Fixed some grammar and spelling.

### CODE REVIEW

**Comment by tbmapman** [comment]
Just remembered I forgot to add in the GPL License sections, so I'll get that done tomorrow.

**Comment by tbmapman** [comment]
I've added the missing GPL section to the gpr.py file.

**Comment by GaryGriffin** [comment]
If this is ready for general release, can you resolve your branch conflicts. Then I can review and merge and publish.

**Comment by GaryGriffin** [comment]
Published

**Pull request merged**
