### PR TITLE
[FamilySheet]Enable CLI & book report usage /Misc help[gramps50]

### PR DESCRIPTION
**Pull request by sam-m888**
* Enable CLI (command line) usage
* Enable book report usage
* Add some help tooltips

### CODE REVIEW

**Comment by lordemannd** [comment]
tested and working on Win64 5beta1-3, in combination with Fix FamilySheet Report for exception on missing spouse # 123
I DID not test the CLI part.

**Comment by sam-m888** [comment]
> tested and working

@lordemannd Thanks for testing.

- [ ] test the CLI part.

**Comment by lordemannd** [comment]
@sam-m888, I am trying to figure out how to test with the CLI part, can you point me to guidance on how to use the CLI in 5.0 on Windows?

**Comment by sam-m888** [comment]
@lordemannd Not sure how you do it on windows with the current AIO installers, but the page to use and update is this:

* [Gramps 5.0 Wiki Manual - Command Line](https://gramps-project.org/wiki/index.php?title=Gramps_5.0_Wiki_Manual_-_Command_Line)

**Comment by lordemannd** [comment]
@sam-m888, I did see that page, but it looks like things have changed, there doesn't seem to be any bin directory and I haven't been able to find the pythonw.exe file under the install directory.

**Comment by sam-m888** [comment]
@lordemannd Yep trying to work it out right now.

**Comment by sam-m888** [comment]
Opening a command window for say the AIO 32 version:

> C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1

and typing 
**gramps -v**

gives  eg:

> C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1>gramps -v
> Gramps Settings:
> ----------------
>  python    : 3.6.4
>  gramps    : 5.0.0-beta2
>  gtk++     : 3.18.9
>  pygobject : 3.26.1
>  pango     : 1.40.11
>  cairo     : 1.15.10
>  pycairo   : 1.16.1
>  osmgpsmap : 1.0
>  GExiv2    : 0.10
>  ICU       : 58.2
>  PyICU     : 1.9.7
>  o.s.      : win32
> 
> Environment settings:
> ---------------------
>  LANG      : en_GB.UTF-8
>  LANGUAGE  : en_GB
>  GRAMPSI18N: not set
>  GRAMPSHOME: C:\Users\me\Documents\gramps-test-profile
>  GRAMPSDIR : not set
>  PYTHONPATH:
>     C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1\gramps
>     C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1
>     C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1\lib
>     C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1\lib/python36.zip
>     C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1\lib\python3.6
> 
>     C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1\lib\python3.6\lib-dynload
> 
> Non-python dependencies:
> ------------------------
>  Graphviz  : 2.40
>  Ghostscr. : 9.22
> 
> System PATH env variable:
> -------------------------
>      C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1
>      C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1
> 
> Databases:
> -------------------------
>  bsddb     :
>      version     : 6.1.0
>      db version  : 6.0.30
>      location    : C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1\lib\python36.zip\bsddb3\__init__.pyc
>  sqlite3   :
>      version     : 3.21.0
>      py version  : 2.6.0
>      location    : C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1\lib\python36.zip\sqlite3\__init__.pyc
> 
> 

and showing the contents of only the executable files:

> C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1>dir *.exe
>  Volume in drive C is Win10-Creator-1709
>  Volume Serial Number is 616B-E3C2
> 
>  Directory of C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1
> 
> 27/01/2018  09:45 AM            27,102 dot.exe
> 26/09/2017  04:29 PM            30,257 fc-cache.exe
> 26/09/2017  04:29 PM            28,744 fc-match.exe
> 05/02/2018  06:14 PM            15,381 gdk-pixbuf-query-loaders.exe
> 23/01/2018  11:59 PM            28,529 glib-compile-schemas.exe
> 27/02/2018  04:55 AM           168,960 gramps.exe
> 27/02/2018  04:55 AM           172,544 grampsd.exe
> 27/02/2018  04:55 AM           151,040 grampsw.exe
> 23/01/2018  11:59 PM            13,318 gspawn-win32-helper-console.exe
> 23/01/2018  11:59 PM            13,318 gspawn-win32-helper.exe
> 15/02/2018  02:55 AM            11,270 gswin32c.exe
> 10/02/2018  04:34 AM            26,461 gtk-update-icon-cache-3.0.exe
> 08/03/2018  01:23 PM           236,250 uninstall.exe
>               13 File(s)        923,174 bytes
>                0 Dir(s)  196,188,311,552 bytes free
>

**Comment by sam-m888** [comment]
Ok CLI works as normal on Win 10 you only have to called the gramps.exe for example to list all the available reports you would do:

**gramps -O "5_0" -a report -p "name="**

> C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1>gramps -O "5_0" -a report -p "name="
> Opened successfully!
> Performing action: report.
> Using options string: name=
> Report name not given. Please use one of [-p|--options] name=reportname
>  Available names are:
>    ancestor_chart            - Ancestor Tree
>    ancestor_report           - Ahnentafel Report
>    birthday_report           - Birthday and Anniversary Report
>    calendar                  - Calendar
>    descend_chart             - Descendant Tree
>    descend_report            - Descendant Report
>    det_ancestor_report       - Detailed Ancestral Report
>    det_descendant_report     - Detailed Descendant Report
>    endofline_report          - End of Line Report
>    family_descend_chart      - Family Descendant Tree
>    family_group              - Family Group Report
>    familylines_graph         - Family Lines Graph
>    fan_chart                 - Fan Chart
>    hourglass_graph           - Hourglass Graph
>    indiv_complete            - Complete Individual Report
>    kinship_report            - Kinship Report
>    navwebpage                - Narrated Web Site
>    notelinkreport            - Note Link Report
>    number_of_ancestors       - Number of Ancestors Report
>    place_report              - Place Report
>    records                   - Records Report
>    rel_graph                 - Relationship Graph
>    statistics_chart          - Statistics Charts
>    summary                   - Database Summary Report
>    tag_report                - Tag Report
>    timeline                  - Timeline Chart
>    WebCal                    - Web Calendar
> Cleaning up.

**Comment by sam-m888** [comment]
Installing this report and running that command adds a new entry:

> FamilyTree                - Family Tree

So in my case for the family tree called "5_0" the command is:

**gramps -O "5_0" -a report -p "name=FamilyTree"**

attempts to create a report, but fails due to the location it attempts to output on gramps

> C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1>gramps -O "5_0" -a report -p "name=FamilyTree"
> Opened successfully!
> Performing action: report.
> Using options string: name=FamilyTree
> Failed to write report.
> Could not create C:\Program Files (x86)\GrampsAIO32-5.0.0-beta1\FamilyTree.odt
> [Errno 13] Permission denied: 'C:\\Program Files (x86)\\GrampsAIO32-5.0.0-beta1\\FamilyTree.odt'
> Cleaning up.

Not sure how to pass the output path for the report.

I'll leave experimenting with the reports options to you, if they are not clear please mention here and 
between us lets see if they can be updated for the wiki.

And sorry that's all the time I have for today (back in 18 hours)

**Comment by lordemannd** [comment]
@sam-m888, excellent, Thank you Sam, I can go from here.

**Comment by sam-m888** [comment]
Your welcome,

For now I've added a warning to that section of wiki, until it can be
updated

https://gramps-project.org/wiki/index.php?title=Gramps_5.0_Wiki_Manual_-_Command_Line#MS_Windows

*Outdated need to add info for new AIO installer CLI usage*
------------------------------

See example usage https://github.com/gramps-project/addons-source/pull/121

**Comment by lordemannd** [comment]
@sam-m888, for your example, setting output file can be something like:
gramps -O "5_0" -a report -p name="FamilyTree",of="C:\Users\<username>\Desktop\FamilyTree.odt"

**Comment by lordemannd** [comment]
@sam-m888, I though I had an account and could edit the wiki, but not working now.

I created a small windows batch file to demonstrate using the CLI. You need to change the extension to ".bat", it has instructions inside the file.
[batch.txt](https://github.com/gramps-project/addons-source/files/1805943/batch.txt)

**Comment by sam-m888** [comment]
> @sam-m888, for your example, setting output file can be something like:
> gramps -O "5_0" -a report -p name="FamilyTree",of="C:\Users<username>\Desktop\FamilyTree.odt"

@lordemannd Thanks I've corrected the example on the wiki, I kept trying with the "="(equals) symbol!

**Comment by lordemannd** [comment]
more examples with Windows CLI:
gramps -O "myDBname" -a report -p show=all
gramps -O "myDBname" -a report -p name="familylines_graph",show=all
gramps -O "myDBname" -a report -p name="FamilySheet",show=all

for continuation lines in batch files: "^" must be last character (before line termination)
for continuation lines in batch files: NO leading white space on following lines

gramps -O "myDBname" -a report -p name="familylines_graph",^
of="c:\Users\me\Desktop\reunion_familylines_graph.pdf",off=gvpdf,^
followchild=True,followpar=True,^
gidlist="I0068 I0079 I0094 I0085",^
incplaces=False,^
incdates=False,justyears=False,^
living_people=99,^
note="[produced %DATE% -- send changes to family_historian@x.com]",noteloc=t,notesize=38,^
papermb="1",paperml="1",papermr="1",papermt="1"

gramps -O "myDBname" -a report -p name="FamilySheet",^
of="c:\Users\me\Desktop\reunion_familysheet_report.pdf",off=pdf,^
incl_notes=False,^
incl_sources=True,^
pid="I0068",^
placeholder=True,^
recurse=2,^
callname=2,^
papermb="2",paperml="2",papermr="2",papermt="2"

**Comment by sam-m888** [comment]
> For many of the options, the "show=all" doesn't give much guidance on what the values are. You can generate the report through the Gramps UI, then find and examine your "report_options.xml" to see how the options are set by Gramps.

Good hint for the wiki 👍

**Pull request merged**
