### PR TITLE
New geography ancestor view

### PR DESCRIPTION
**Pull request by SNoiraud**

### CODE REVIEW

**Comment by sam-m888** [comment]
Screenshot with no family tree open. (  Icon not displayed (but file ( geo-ancestor.svg ) is present in addons directory folder ( GeoAncestor ) ) Win 10 64 bit Gramps AIO 5.1.2
geo-ancestor-map-icon

> 
> (gramps.exe:9852): OsmGpsMap-CRITICAL **: Map source setup called twice
> (gramps.exe:9852): Gtk-WARNING **: drawing failure for widget 'OsmGpsMap': NULL pointer
> (gramps.exe:9852): Gtk-WARNING **: drawing failure for widget 'GtkBox': NULL pointer
> (gramps.exe:9852): Gtk-WARNING **: drawing failure for widget 'GtkPaned': NULL pointer
> (gramps.exe:9852): Gtk-WARNING **: drawing failure for widget 'GtkPaned': NULL pointer
> (gramps.exe:9852): Gtk-WARNING **: drawing failure for widget 'GtkNotebook': NULL pointer
> (gramps.exe:9852): Gtk-WARNING **: drawing failure for widget 'GtkPaned': NULL pointer
> (gramps.exe:9852): Gtk-WARNING **: drawing failure for widget 'GtkBox': NULL pointer
> (gramps.exe:9852): Gtk-WARNING **: drawing failure for widget 'GtkApplicationWindow': NULL pointer
> (gramps.exe:9852): OsmGpsMap-CRITICAL **: Map source setup called twice

**Comment by SNoiraud** [comment]
The only problem I have is the icon.
I never saw the Gtk warning problems you have. Only tested on my linux with a database.

**Comment by SNoiraud** [comment]
How to add it to the available plugins ?

**Comment by prculley** [comment]
For addons, you have to do the icons like GraphView, HTreePedigreeView etc.  Unless the icon is already a standard part of Gramps.

Adding the addon requires making the plugin with the GrampsAddons mak.py script.  I use
python3 make.py gramps51 as-needed
but only after making sure that your copy of the GrampsAddons and addons git is up to date.  The script will scan everything and build anything that needs building, however if your addon is the most recently merged one, it should be the only one that actually gets done.  You can look at the script to see some other variations for only doing one addon.

Once made, git add and git commit both GrampsAddons and addons and push them back to their proper branches (maintenance/gramps51 and master).

**Comment by prculley** [comment]
Or you could wait until Sam or I does the process...

**Pull request merged**
