### PR TITLE
Add new [Avatar Generator] addon [gramps50]

### PR DESCRIPTION
**Pull request by Mattkmmr**
I created a new addon 'AvatarGenerator'. It allows users to add and remove one or serveral images to a group of filtered people. Users can choose the images from their database. The selected avatar images are only added to people without an image.

Screenshot of the Tool:
AvatarGeneratorTool

Before & After:
Avatar_Generator

### CODE REVIEW

**Comment by wroldwiedbwe** [comment]
> Before & After:

are you missing the after screenshot?

**Comment by Mattkmmr** [comment]
The animated gif shows the before and after screenshot. Is it not visible for you?

**Comment by wroldwiedbwe** [comment]
> The animated gif shows the before and after screenshot. Is it not visible for you?

No it is a static image for me!

**Comment by adamvazquez82** [comment]
https://github.com/gramps-project/addons-source/pull/207

**Pull request closed without merging**
