### PR TITLE
DescendantsLines addon: several improvements

### PR DESCRIPTION
**Pull request by giansalvo**
- added left and right margins
- renamed options to be more user friendly
- added same width, same height options
- added header and footer and font size coeff
- added some comments to the code
- rearranged options to reduce size on screen

### CODE REVIEW

**Comment by prculley** [comment]
Looks ok to me...

**Comment by giansalvo** [comment]
@prculley Thanks for your feedback

> We try to make sure that dialogs/windows fit onto an 800x600 screen, I think this is getting too tall for that. Maybe we need another tab or two. Consider putting the three 'display format' boxes in their own tab, header/footer text near privacy text, and possibly in a tab of its own. And rearrange the report options and display to hold items more evenly in height.
> 
ok, I can do this

> I see you tried to add better tooltips and descriptive names to some of the options in the last two tabs, but could you try for better names for the tabs themselves? What is S&F or O&C? And you missed a couple MIN_C_WIDTH and OL_PAD.
> 
I didn't miss those parameters, I just can't understand what they do.
Please let me know what you want to put instead of S&F and O&C and I'll be happy to substitute them.

**Comment by SNoiraud** [comment]
You have many trailing spaces:
DescendantsLines/DescendantsLines.py:255:        MIN_C_WIDTH - 
DescendantsLines/DescendantsLines.py:695:        
DescendantsLines/DescendantsLines.py:1608:        
DescendantsLines/DescendantsLines.py:1774:        
DescendantsLines/DescendantsLines.py:1792:        
ERROR - Trailing whitespace found in source file(s)

**Comment by giansalvo** [comment]
@SNoiraud 
I removed the trailing spaces. I had a problem with my editor's settings. It should be fixed now.

**Comment by prculley** [comment]
Because of minor file merge conflicts, I had to do this manually.  It is accepted and uploaded.

**Pull request closed without merging**
