### PR TITLE
Add new Tool [FamilyRelationshipTool]

### PR DESCRIPTION
**Pull request by Mattkmmr**
Requested in [#2656](https://gramps-project.org/bugs/view.php?id=2656)

> (1) Families - when the Relationships of a long list of named fathers and mothers are shown as "Unknown", to change all the "Unknown" to "Married" as a batch.

### CODE REVIEW

**Comment by wroldwiedbwe** [comment]
Tried to test but only get the following errors and a crash

2020-05-18 17:59:42.968: WARNING: _enumeratedlist.py: line 143: Value '0' not found for option 'Family Filter'
2020-05-18 17:59:42.974: WARNING: _enumeratedlist.py: line 144: Valid values: []
2020-05-18 17:59:43.014: WARNING: _enumeratedlist.py: line 143: Value '0' not found for option 'Family Filter'
2020-05-18 17:59:43.014: WARNING: _enumeratedlist.py: line 144: Valid values: []

71446: ERROR: grampsapp.py: line 157: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.2\gramps\gui\plug\_windows.py", line 807, in on_ok_clicked
    self.run() # activate results tab
  File "C:\Users\wroldwiedbwe\Documents\gramps\gramps51\plugins\FamilyRelationshipTool\FamilyRelationshipTool.py", line 85, in run
    filter_ = self.__opt("families").get_filter()
  File "C:\Program Files\GrampsAIO64-5.1.2\gramps\gen\plug\menu\_filter.py", line 80, in get_filter
    return self.__filters[self.get_value()]
IndexError: list index out of range

It also locks up Gramps!! and had to use task manager to kill it.

lockedup

**Comment by Mattkmmr** [comment]
@wroldwiedbwe Have you created and used a family filter or just pressed execute? 😄

**Comment by wroldwiedbwe** [comment]
> Have you created and used a family filter or just pressed execute? 😄

I just pressed execute in my test assuming it would do nothing ¯\_(ツ)_/¯ and I was wrong.

**Comment by Mattkmmr** [comment]
@wroldwiedbwe I updated the tool. If you now try to run it without custom family filters you have an option to run the tool on all families by default.

**Comment by wroldwiedbwe** [comment]
Worked, could not get Gramps to lock up this time.

updated1

One suggestion is to rename the menu entry to remove the word "Tool" so it is like the rest of the entries.

menu


Thanks for the update 🥇

**Pull request merged**
