### PR TITLE
[GraphView] Gtk theme support[Gramps51]

### PR DESCRIPTION
**Pull request by vantu5z**
Should be merger with https://github.com/gramps-project/gramps/pull/523

If dark theme is used - white background looks not good.
- get colors from gtk theme;
- colors for persons and families gets from gramps settings;
- color of links set to font color;

### CODE REVIEW

**Comment by sam-m888** [comment]
Looks good.

Dark theme with Gramps default theme.
pr51-graphview-use-dark-theme-enabled-default-hpc

I believe that the **Home person**'s background is too bright maybe try `#4e9a06` for the color?
pr51-graphview-use-dark-theme-enabled-suggested-hpc-color-4e9a06

**Comment by vantu5z** [comment]
I don't know how to change home person color when switch theme and apply them.
This color can be selected by user from settings then i don't find solution long.
Any advise?

**Comment by vantu5z** [comment]
For me it looks like this. With #304918 color for home person.

**Comment by sam-m888** [comment]
> I don't know how to change home person color when switch theme and apply them.
> This color can be selected by user from settings then i don't find solution long.

Not sure, possibly leave it up to the user for now and improve it later.

**Comment by enlite93** [comment]
IMHO the **Use dark theme** check box would be better in Gramps global preferences, instead of on an individual Addon basis!

**Comment by Paul-Franklin** [comment]
I am not a GUI expert but after a quick glance at the code ISTM
that this report is controlling its colors at a very detailed level --
and is now offering another set of built-in color choices, calling it
a "dark theme."

But insofar as I understand it, it is not really a "theme" in the
(global) Gnome sense, something which affects all programs
on a user's computer.

The last time I remember reading anything about that sort
of thing I had the impression that the experts were saying
it is not possible for a client program to change a global
theme setting.  That there was no Gtk3 API to do that.

But of course I could be wrong and if you know enough
to know how that can be done, please feel free to file a
gramps feature request -- with the Gtk3 API details please.

Thanks.

**Comment by enlite93** [comment]
@Paul-Franklin @sam-m888 A working tested (by me) patch to enable the GTK dark theme variants for Gramps is available on 7749 ( [7749-gtk312-dark-theme.diff](https://gramps-project.org/bugs/file_download.php?file_id=7030&type=bug) ) mentioned above.  I'm only suggesting that it be added to Gramps with a checkbox and then this addon can pick up from a variable that a dark theme is in use eg: `dark_theme_set`  or possibly  `ui.dark_theme_set`

**Comment by SNoiraud** [comment]
Sorry, I have modified  graphview.gpr.py to resolve bug 7393.

**Comment by romjerome** [comment]
> Sorry, I have modified graphview.gpr.py to resolve bug 7393.

@SNoiraud ,
I see this message on current automatic "conflict" check (github web interface):
> This branch has no conflicts with the base branch
does it mean that we could have a confict somewhere, anyway?

**Comment by sam-m888** [comment]
As it does not look like Gramps will get a global Dark theme anytime soon and this PR on makes the canvas area for Graphview dark that I will merge this PR after PR #88 has been merged.

Then if Gramps does get a global dark theme this setting can be removed from Graphview and made to honor the global one.

**Comment by sam-m888** [comment]
Retesting this PR it of course has the issues mentioned in my comment https://github.com/gramps-project/addons-source/pull/51#issuecomment-244536343 I also notice that after applying the PR the colors for the standard light color them also have changed.

Original light theme Graphview colors no patch
original-graphview-colors-no-patch

Graphview  light theme  colors with patch
graphview-colors-with-patch

Graphview dark theme with patch
darktheme-graphview-colors-patch

**Comment by vantu5z** [comment]
This is another feature included in this PR. Dead people looks more smooth.

**Comment by sam-m888** [comment]
> This is another feature included in this PR. Dead people looks more colorless.

Yes looking at this PR's  first message you clearly state "**another color of boxes for dead people;**"  unfortunately it was not clear that was the reason for the change of color, image how normal users will react? Are you aware of Gramps ["Colors" tab in preferences](https://gramps-project.org/wiki/index.php?title=Gramps_5.0_Wiki_Manual_-_Settings#Colors) that allows you to "Set the colors used for boxes in the graphical views"  it defines colors for Alive & Dead and each of the Gender settings?

**Comment by vantu5z** [comment]
Hm, I think we should get colors from config instead of hard coded. And background and font color get from gtk theme. I look what I can do :)

**Comment by vantu5z** [comment]
Ok. What I do:
- background and font colors gets from the current gtk theme.
- colors for persons gets from gramps settings.
- colors for family nodes hard coded.
- colors for links is set to font color.
- in config dialog option is still present (to choose dark presets without changing grams settings).
And PR was rebased.

I found issues:
- printing function with dark theme works, but regular user don't want to print dark version of view I think. Or should have choice of presets.
- not all views support colors from gtk and may have issues with text if user change colors in grams settings.

As solution:
- we need presets of colors in gramps settings (light, dark, print) that can be configured separately.

**Comment by PQYPLZXHGF** [comment]
@vantu5z You may want to sign up for travis-ci emails as your last [commit failed](https://travis-ci.org/gramps-project/addons-source/builds/274150132#L2366) due to 

```
GraphView/graphview.py:1389:            'family_fill'         : '#454547' 
ERROR - Trailing whitespace found in source file(s)
```

**Comment by sam-m888** [comment]
> we need presets of colors in gramps settings (light, dark, print) that can be configured separately.

Yes, shows that Gramps itself needs to be modified to support a [darktheme](https://github.com/gramps-project/addons-source/pull/51#issuecomment-247747829)

2017-09-17 11_52_17-ubuntu-16 04 1-grampsdev-amd64 running - oracle vm virtualbox

**Comment by vantu5z** [comment]
With light theme and without dark presets:


With dark theme and without dark presets
(if theme is not dark much and colors not pretty good,
it can be selected from gramps config dialog, excluding family nodes color):



With dark theme and with dark presets:

**Comment by SNoiraud** [comment]
I think this is not the solution. We should use the preferenced colors either for dark theme or not.
Others views like Pedigree use these colors.
So in the Pedigree view, we'll must change these values for the dark theme.
So we could use them for Graphview.

**Comment by SNoiraud** [comment]
I tried to use the global preferences for the colors. It works for me.
In these case, I think the dark theme button option is useless.
The only remaining problem is the family fill color. We could replace the dark theme with a color chooser like for the "path color"
I add my last patch for this.

**Comment by SNoiraud** [comment]
[patch5.patch.txt](https://github.com/gramps-project/addons-source/files/1573191/patch5.patch.txt)

**Comment by SNoiraud** [comment]
[patch6.patch.txt](https://github.com/gramps-project/addons-source/files/1573205/patch6.patch.txt)

**Comment by sam-m888** [comment]
@vantu5z Some theme work on Gramps has been done by @Nick-Hall see https://github.com/gramps-project/gramps/pull/506

**Comment by vantu5z** [comment]
@SNoiraud , dark theme checkbox was removed and color chooser added for family node.
We use global gramps colors for persons boxes.
That look good but for well configuration we need schemes of colors presets for global gramps colors:
- light
- dark
- custom
- printing

**Comment by vantu5z** [comment]
This PR should be applied to gramps50, because PR was merged with gramps 50 https://github.com/gramps-project/gramps/commit/028f9582f58ca0c8e38986829e0bceab1b3135f5

**Comment by daleathan** [comment]
> This PR should be applied to gramps50, because PR...

Great stuff with fixing theming and the aninmation you added👍  My guess is that you'll have to rebase it on Gramps50 due to the other changes that vesion of graphview has that gramps mastEr doesn't.

**Comment by PQYPLZXHGF** [comment]
Does [gramps51](https://github.com/gramps-project/gramps) need to be updated with the changes from gramps50 to use this?

**Comment by vantu5z** [comment]
> Does gramps51 need to be updated with the changes from gramps50 to use this?

Yes, gramps50 should be merged to master.

**Comment by sam-m888** [comment]
Addon rebuilt for gramps50 in commit:
https://github.com/gramps-project/addons/commit/5357ae577552b0e246372eb394c3e5d9d4448f24

Thank you

**Pull request merged**
