### PR TITLE
[GraphView] another way to display tags

### PR DESCRIPTION
**Pull request by vantu5z**
Tags display by color lines in the bottom of person box.
It looks like this:

### CODE REVIEW

**Comment by vantu5z** [comment]
I can't understand why tags not shown on home person (when it highlight).

**Comment by SNoiraud** [comment]
The second commit doesn't work for me.
If I change 'transparent' by 'none', it's OK.
I don't know where none is loaded in gramps!

**Comment by SNoiraud** [comment]
Do you use styles? perhaps this is the difference. Neither transparent or none are present in gramps sources.
I think these values come from graphviz.

**Comment by vantu5z** [comment]
Yes, I think it come from graphviz.
I just insert print():
```
if self.highlight_home_person:
            print(attrs)
```
and get strings like this:
```
...
{'fill': '#b9cfe7', 'stroke': '#204a87', 'points': '4853,-974 4608,-974 4608,-811 4853,-811 4853,-974'}
{'fill': '#efb60c', 'fill-opacity': '0.156863', 'stroke': 'transparent', 'points': '4620.5,-818.5 4620.5,-828.5 4841.5,-828.5 4841.5,-818.5 4620.5,-818.5'}
{'fill': '#b9cfe7', 'stroke': '#204a87', 'points': '4474,-455.5 4379,-455.5 4379,-419.5 4474,-419.5 4474,-455.5'}
...
```

**Comment by vantu5z** [comment]
For me works this:
`if self.highlight_home_person and (not attrs.get('fill-opacity')):`

**Comment by SNoiraud** [comment]
OK. You have 'stroke' in the attrs. This is the reason you have 'transparent'.
I don't know the reason you have that.
For me, colors always begin with '#'. Yours too. Perhaps we could change the if statment by : 
if self.highlight_home_person and stroke_color[:1] == '#':

**Comment by SNoiraud** [comment]
I don't have fill-opacity. I only have the following : 
attrs : {'points': '9497,-981.5 9497,-991.5 9714,-991.5 9714,-981.5 9497,-981.5', 'fill': '#edd400', 'stroke': 'none'}

**Comment by vantu5z** [comment]
OK, that we should to check if it is a color like you suggested.

**Comment by SNoiraud** [comment]
As we are trying to add tags to people, it could be usefull to do the same thing for families.
I already have something for that.

**Comment by SNoiraud** [comment]
Here is my first try. Does it work for you.
I added the possibility to refresh the screen when we change the show tags button.

[show_tags.txt](https://github.com/gramps-project/addons-source/files/1268564/show_tags.txt)

**Comment by vantu5z** [comment]
Yes, it works. But I think it should be like this.

**Comment by vantu5z** [comment]
And look like this:

**Comment by SNoiraud** [comment]
Perhaps we could add this to gramps 5.0. It's a really nice feature.

**Comment by vantu5z** [comment]
I would like to see it in gramps 5.0 too.

**Comment by vantu5z** [comment]
Should we show this PR for some one else or can merge it?
And who decide if it go to gramps 5.0?

**Comment by SNoiraud** [comment]
I think you can merge it.
As this is a addon module, I think this is to the developper to decide.
Perhaps Sam ( @sam-m888 ) could confirm this.

**Comment by sam-m888** [comment]
> As this is a addon module, I think this is to the developper to decide.

@SNoiraud Yes Addons are handled by the original developer or whoever contributes to it.  So if a gramps50/[42](https://github.com/gramps-project/addons-source/pull/86#issuecomment-326538632) pr are made I will rebuild the addon for you @vantu5z 

Very good enhancement 👍 

Suggestion is it possible to:

* have a legend of what each color tag is?
* or display a tooltip when you hover over the color ?
* or possibly partially display the tag name in the tag box?

**Comment by vantu5z** [comment]
Make PR #87 for gramps50 branch

**Comment by sam-m888** [comment]
Rebuilt for Gramps master as https://github.com/gramps-project/addons/commit/2cbceca0f8fa9c0be1ebf20cb8f0c880b31a129d

**Comment by sam-m888** [comment]
Thanks you for merging, really would have preferred that you let someone review that it works as advertised in case of a major issue so that it does not get pushed out to normal users.

So thanks for adding the legend for tags, unfortunately after looking a bit closer (image below) you can see that the colors for the tags don't match those in the legend table.

img_20170908_130447727

**Comment by vantu5z** [comment]
I don't know why colors of tags at graph differ from legend (in legend correct). But, if you open tag in tag manager and resave it, it will be shown correctly.

**Comment by sam-m888** [comment]
> Maybe gramps example tree have tags colors in other format that used befor.

Not as far as my testing shows so far!

**Pull request merged**
