### PR TITLE
Select Form Dialogs fixes and improvements, inc search filtering

### PR DESCRIPTION
**Pull request by dbareis**
* Smaller targetted change as requested by (1 changed, 2 new files):
   https://github.com/gramps-project/addons-source/pull/349

* Cancel button now works (no longer performs OK's function)

* OK button now performs validation, only continues where possible.

* Added help button

* Can no longer get multiple exceptions from the dialog (no longer need to kill gramps or respond to many exception dialogs to recover).

* CTRL+F (or just start typing) interactive search now works in the form selection dialog.  It filters out mismatches.  Matches are case insensitive and match anywhere in the string.

AllChoicesShown+FullyExpanded
Filtered for vic
Filtered for ustr

* Added Reset filter (doubles as an expand tree button)

* Added compact/compress tree button.

* The form title wasn't being used.
    It now optionally is (it is if it begins with '/').
    e.g. title='/path1/subpath1.1/subpath1.1.1/census 1990'

* when the form title isn't used then the dialog puts legacy entries into the same tree roots as in the past but may organise them by country or state below that.
    A Denmark census would be in the path 'Census/Denmark'.
    It also continues to use the source's name/title as the description (that is the title is ignored as previously).

    Filtering by "Denmark" is an easy way to get to them. In the US you can filter by state, or year of the census.

    EXAMPLE TITLES
    ~~~~~~~~~~~~~~
    title="/Death/World Wide/Find a Grave (https:{s}{s}www.findagrave.com{s})"
    title="/Birth/Australia/Queensland (registry)"

* The size of the select dialog can be modified from the default INI value
   "form.ini".

* hover expand turned off by default, can be enabled from an INI value

* some functions required by future updates

### CODE REVIEW

**Comment by dbareis** [comment]
I am really hating GitHub (and the fact that "Forms" isn't it's own repository), but maybe answers to the following will help (online):

Q1: Is there any way to sort the files by modified time?

Q2: Is there any way to just compare my changes? I don't want to see everyone else's and wonder if they are mine by accident etc

Q3: I can't see any way I can work on multiple things at once as pulls work on the whole repository and not selected files and you can't fork a project more than once.

**Comment by prculley** [comment]
It looks like you have reset the base to maintenance/gramps51, but not actually 'rebased' the branch onto that branch.  As a result, all changes from the original (probably master) branch got included here.

I am not aware of any way to perform this rebase strictly on Github.  My (and most other people) way of doing this is to do the work on my local machine with the 'git' toolset.  Github is usually just used as the public repository, although its few tools might cause one to think that it is suitable for everything.  A tutorial on the 'git rebase' command is https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase, that site is pretty good in describing the various procedures in using git.

**Comment by jralls** [comment]
The [Official Git Documentation](https://git-scm.com/doc) includes an online, free-to-read, version of Scott Chacun's very excellent *Professional Git*. It will take you from noob to expert in 6 chapters.

**Comment by Nick-Hall** [comment]
@dbareis This change looks good and is now a reasonable size for review.  I can see a few issues with the implementation, but nothing that can't be fixed.  Please rebase as suggested.

**Comment by dbareis** [comment]
Thanks, guys,  I'm using Github and not Git.  Unless someone tells me its a major mistake for some reason, I'm going to archive (or delete) my repository.  That should allow me to re-fork a new one from maint 51.

I put some questions up in the get request, they are my main problems.  I can't see how I can be working on multiple things at once.

If (as I recently did) I upload files to a new branch (from DennisBareis) and made a get request, that was to myself and not the maint branch.  That is the only way I can see having multiple get requests on the go.  Unless there is a way I can create branches off maint 51?

https://github.com/dbareis/addons-source/pull/1
dbareis wants to merge 1 commit into **DennisBareis** from **dbareis-selectform-improvements**

**Comment by prculley** [comment]
I can understand not wanting to take on git...  But many of the things that need to be done can only be done via git.  That said, I think that Github does allow branches; you might want to review their help pages https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository.

**Comment by dbareis** [comment]
Thanks for that but as above, I did try a branch, if that is somehow correct after all and it can be retargeted to the maint, then please let me know.

dbareis#1
dbareis wants to merge 1 commit into **DennisBareis** from dbareis-selectform-improvements

**Comment by Nick-Hall** [comment]
Something went wrong with the rebase.  This PR now contains 42 commits.  Most of them are not relevant to the change.

**Comment by dbareis** [comment]
Giving up this branch, will give it one more go before giving up for good.

**Comment by Nick-Hall** [comment]
@dbareis If you decide to give up, perhaps you could email me the files for this change.

**Comment by dbareis** [comment]
Hi,

I haven't given up yet but definitely close. Can you please have a look
at:  https://github.com/dbareis/DB_gramps_addons-source/pull/1

---
Thanks
Dennis

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
28/05/20,
09:10:41 am

**Pull request closed without merging**
