### PR TITLE
New version of PrerequisiteCheckerGramplet and some troubleshooting.

### PR DESCRIPTION
**Pull request by SNoiraud**
1 -  New version imported from Bug report 012769
    
    The text reformatting includes:
        swapping in leading spaces & bullets for asterisks.
        italicizing descriptive text
        composing backup text and correcting menu labels
        making the Required-Recommended-optional section labels more consistent in tense
    
    Updated Help URLs
       Changed & tested the Help URLs to the new standard "Addon:" prefix and added a
       "in document" scrolling target. (Including the help_url in this repository's Gramps
       Plugin's Registration file.)
    
2 -  PrerequisitesChecker gramplet: Gexiv2 and ICU
    
    Detection of these libraries does not work or partially.
    
3 - If the Prerequisites Checker Gramplet is active when Gramps start, the Gramplet runs the report 3 times

Fixes #012767, #012769, #012770

### CODE REVIEW

**Comment by emyoulation** [comment]
After copying over the source, the Gramplet only shows "Diagnostic Gramplet to help evaluate if Gramps has all prerequisites installed." and stops.

**Comment by emyoulation** [comment]
I had not tried it as a Dashboard. (My dashboard is Full. So it is an awkward place for this Gramplet that will normally be used once and then be unloaded. Since it needs maximum vertical space, it fits the sidebar best.)

In the sidebar and the ”self.count = 3”, the report only shows Twice when loading a different tree database. That's a rare situation - so it is livable. 

It no longer shows Multiple reports if the Hramplet is loaded when you restart Gramps. (Restarts are likely if the user is trying to fix one missing perequisites at a time.)

But WITHOUT the "self.count = 3”, the sidebar only shows the 1st line of the report. That is not usable.

**Comment by SNoiraud** [comment]
> But WITHOUT the "self.count = 3”, the sidebar only shows the 1st line of the report. That is not usable.

NO. as we are in a list view, the database must be opened. It works like that. I’m not changing that.
I think this plugin is heresy. You have gramps -V to have the same results.

**Comment by emyoulation** [comment]
Sorry, I had Gramps set to autoload the last used Tree but turned that feature off for the previous bug test.

I've removed the override on my installation. 

Thank you for including the updated help_url s

**Pull request merged**
