### PR TITLE
New filter rule [peopleeventscount]

### PR DESCRIPTION
**Pull request by Mattkmmr**
Filter for persons which have multiple events of given (event) type.
Requested in [#5494](https://gramps-project.org/bugs/view.php?id=5494)

### CODE REVIEW

**Comment by emyoulation** [comment]
Could you change this to search for a `<count>` instead of multiple? Then it could be used for zero counts, single counts & more than 2 counts too.

Please consider renaming to "`People with <count> of <event>`"

**Comment by Mattkmmr** [comment]
@emyoulation You can already search for people with 0 occurences of an event of a certain type with existing filters. Person filter **persons with event** e.g. birth events, then inverse results.

**Comment by emyoulation** [comment]
That's true. But... if this rule had that capability plus single count, plus >zero, plus >n; then we could justify a request to Eliminate the single purpose rules ... which simplifies selection of rules for confused users.

**Comment by Mattkmmr** [comment]
Maybe it'd be more universal to add the counter to the built-in filter rule `People with the personal <event>` instead.

**Comment by emyoulation** [comment]
That makes sense but would that work? The rule name would have to be changed to include `<count>` either way. If the rule name changes, is it the same Rule?

On the flip side, since this would be an enhancement & in the core, which means it cannot go public until the 5.2 release. And any non-bug tweaks would be delayed until the NEXT enhancement release. Worse, the prototype only get tested by users with Development level tech skills. Not the average users who do unexpected & sometimes illogical things.

That throttles evolution too severely. The Core enhancement cycle is just too rigid to get fast, comprehensive evolution.  

So an add-on that can evolve quickly then supplant the core function when stable would seem to be the best trade-off in choices.

**Comment by Mattkmmr** [comment]
@emyoulation I rewrote the filter rule and renamed it to `People with <count> of <event>`. It has now a number field and "greater than", "equal", "smaller than" selector. It also got a checkbox for the primary event roles. 😄

**Comment by prculley** [comment]
Built and in addons repo.  Thanks.

**Pull request merged**
