### PR TITLE
[GraphView] Add search capability[gramps50]

### PR DESCRIPTION
**Pull request by vantu5z**
Снимок экрана от 2019-03-25 11-32-40

### CODE REVIEW

**Comment by vantu5z** [comment]
Снимок экрана от 2019-03-27 10-10-18

**Comment by vantu5z** [comment]
Снимок экрана от 2019-03-28 11-25-59

**Comment by vantu5z** [comment]
Have some problem, I use methods to set max size of scroll windows that came from Gtk 3.22:
```
ScrolledWindow.set_max_content_height(200)
ScrolledWindow.set_propagate_natural_height(True)
```
And for now can't find some solution or workaround.

**Comment by vantu5z** [comment]
@SNoiraud can you test it? Maybe you have some other ideas to include?

**Comment by SNoiraud** [comment]
Tested. it's OK for me. I don't see something new to add.

**Comment by SNoiraud** [comment]
Perhaps. Do you mean to search someone in the database then bookmark him?

**Comment by vantu5z** [comment]
No. Now we show bookmarks only for graph and other bookmarks are hidden. I suggest add this bookmarks to second scroll window like in the search popup.

**Comment by SNoiraud** [comment]
OK.

**Comment by SNoiraud** [comment]
It could be interesting to bookmark a person from the menu (right button: edit, edit tags...)

**Comment by vantu5z** [comment]
Yes, I think about this too.
But think it should be separate PR like: right click popup enhancement
Related issue about tags https://gramps-project.org/bugs/view.php?id=10870

**Comment by SNoiraud** [comment]
It could be interesting to bookmark a person from the menu (right button: edit, edit tags...)

**Comment by PQYPLZXHGF** [comment]
> [Have some problem, I use methods to set max size of scroll windows that came from Gtk 3.22:](https://github.com/gramps-project/addons-source/pull/195#issuecomment-477688428)

@vantu5z You probably want to take the advice [here](https://github.com/gramps-project/gramps/pull/783#issuecomment-481321833) by @Nick-Hall that only properties that work on Gtk v3.12 be used for Gramps v5.1 and for the current Gramps 5.0 or older only use Gtk v3.10 properties.

**Comment by sam-m888** [comment]
Please ensure that it works with gtk 3.10 as mentioned. Thank you

**Comment by vantu5z** [comment]
Workaround was added for gtk 3.10, but I can't test it on gtk 3.10. If some one make test it will be nice.

**Comment by adamvazquez82** [comment]
I really like the search box, maybe somehow it can be integrated into the toolbar so you can use it all over Gramps, what do you think? Or should I raise a feature request?

55165883-ef8efa80-514c-11e9-91eb-05dfe7070b81

**Comment by vantu5z** [comment]
Should results popup be closed on click some item?

**Comment by vantu5z** [comment]
rebased

**Comment by vantu5z** [comment]
rebased after PR #199 revert

**Comment by vantu5z** [comment]
Seems that it requires Gtk 3.12 because of Gtk.Popover.
So it should go to Gramps 5.1 ([link](https://github.com/gramps-project/gramps/pull/783#issuecomment-481321833))

**Pull request closed without merging**
